#!/usr/bin/env python3
"""
widgetkit-src build tool.

Usage:
  python3 build.py render <kit> [widget ...] [--force]
      Render specs/*.yaml (or just the named widgets) into parts/<name>.png
      + parts/<name>.json. Only touches widgets you name, or ones with no
      parts/ file yet -- pass --force to also overwrite named widgets that
      already have rendered parts.

  python3 build.py pack <kit>
      Read every parts/*.png + .json pair, pack them into the atlas,
      regenerate the header's two generated sections (the Colors:: constants,
      from palette.yaml's exported_colors, and the Skins::), rebuild
      preview.html, and copy the atlas + header to their real repo
      locations (resources/, src/widgetkits/).

Directory layout expected (kit_dir = widgetkit-src/<kit>/):
  palette.yaml
  specs/<Name>.yaml
  parts/<Name>.png, parts/<Name>.json      (generated by `render`)
  header_shell.h                            (hand-maintained)
  preview.html, <kit>_skinblocks.png, wg_<kit>.h   (generated by `pack`)
"""
import argparse
import json
import re
import sys
from pathlib import Path

import yaml
from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).parent))
import theme_lib as T

REPO_ROOT = Path(__file__).resolve().parents[2]
KIT_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_DENSITY = 2

# Render styling per State name: which palette entry to use, how much gloss,
# how much inward "pressed" shading, and overall opacity. This table is
# rendering logic (a "recipe" concern), not per-kit data, so it lives in code.
STATE_STYLE = {
    "Default":         dict(pal="raised",        gloss=150, inset=0,  alpha=1.0),
    "Hovered":         dict(pal="hover",          gloss=185, inset=0,  alpha=1.0),
    "Pressed":         dict(pal="pressed",        gloss=40,  inset=70, alpha=1.0),
    "Disabled":        dict(pal="disabled",       gloss=25,  inset=0,  alpha=0.82),
    "Checked":         dict(pal="checked",        gloss=60,  inset=55, alpha=1.0),
    "CheckedHovered":  dict(pal="checked_hover",  gloss=90,  inset=35, alpha=1.0),
    "CheckedPressed":  dict(pal="pressed",        gloss=25,  inset=95, alpha=1.0),
    "DisabledChecked": dict(pal="disabled",       gloss=15,  inset=40, alpha=0.82),
}


def glyph_color(palette, state):
    return palette["glyph_disabled"] if state in ("Disabled", "DisabledChecked") else palette["glyph_white"]


def render_state_block(spec, palette, state, w_px, h_px, density):
    radius_px = T.px(spec.get("radius_pts", 0), density)
    shape = spec.get("shape", "rect")
    border_px = max(T.px(1.2, density), 1)

    style = STATE_STYLE[state]
    # STATE_STYLE names a palette entry per state ("raised", "hover", ...).
    # `palette_family` prefixes those, so a kit can carry more than one family
    # of control colours -- e.g. `plate` for controls that should read as
    # furniture rather than accents -- without duplicating the state table.
    family = spec.get("palette_family")
    pal = palette[f"{family}_{style['pal']}" if family else style["pal"]]
    img = T.raised_panel(w_px, h_px, radius_px, pal, border=border_px,
                          gloss_alpha=style["gloss"], shape=shape,
                          gloss_frac=spec.get("gloss_frac", 0.5),
                          ease=spec.get("gradient_ease", 1.0))
    if style["inset"] > 0:
        img = T.inset_shade(img, w_px, h_px, radius_px, amount=style["inset"], shape=shape, border=border_px)
    if style["alpha"] < 1.0:
        r, g, b, a = img.split()
        a = a.point(lambda v: int(v * style["alpha"]))
        img = Image.merge("RGBA", (r, g, b, a))

    glyph = spec.get("glyph")
    if glyph:
        gtype = glyph["type"]
        gcolor = glyph_color(palette, state)
        outline = palette["glyph_outline"]
        if gtype == "arrow":
            # Default proportions match the select box's arrow (base twice the
            # base-to-tip depth), transposed for the horizontal directions.
            dw, dh = (10, 5) if glyph["direction"] in ("up", "down") else (5, 10)
            img = T.add_arrow_glyph(img, glyph["direction"], gcolor, outline,
                                    T.px(glyph.get("arrow_w_pts", dw), density),
                                    T.px(glyph.get("arrow_h_pts", dh), density))
        elif gtype == "plusminus":
            mode = "minus" if state.startswith("Checked") else "plus"
            img = T.add_plusminus_glyph(img, mode, gcolor)
        elif gtype == "check":
            if state in ("Checked", "DisabledChecked"):
                img = T.add_check_glyph(
                    img, gcolor,
                    check_w_px=T.px(glyph["check_w_pts"], density) if "check_w_pts" in glyph else None,
                    check_h_px=T.px(glyph["check_h_pts"], density) if "check_h_pts" in glyph else None,
                    stroke_px=T.px(glyph["stroke_pts"], density) if "stroke_pts" in glyph else None,
                    outline=outline if glyph.get("outline", False) else None)
        elif gtype == "dot":
            if state == "Checked":
                img = T.add_dot_glyph(
                    img, gcolor,
                    dot_px=T.px(glyph["dot_pts"], density) if "dot_pts" in glyph else None,
                    outline=outline if glyph.get("outline", False) else None)
        elif gtype == "grip":
            # Ridges run ACROSS the axis the handle is dragged along, so a wide
            # handle gets vertical lines -- the opposite of what the block's
            # aspect ratio suggests, which is how this got reversed before.
            # Stated per-spec; the fallback follows the same rule.
            direction = glyph.get("direction") or ("vertical" if w_px >= h_px else "horizontal")
            img = T.add_grip_lines(img, f"{direction}_lines", palette["grip_hi"], palette["grip_lo"],
                                   T.px(glyph["len_pts"], density) if "len_pts" in glyph else None)
        elif gtype == "dotgrid":
            img = T.add_dot_grid(img, palette["grip_hi"], palette["grip_lo"])
        elif gtype == "dots":
            # Dots line up ALONG the bar, which is the split panel convention
            # (unlike scrollbar grip ridges, which run across the drag axis).
            img = T.add_dot_line(img, glyph["direction"], glyph.get("count", 3),
                                 T.px(glyph.get("dot_pts", 2.5), density),
                                 T.px(glyph.get("gap_pts", 4), density),
                                 palette.get("dot_hi", palette["grip_hi"]),
                                 palette.get("dot_lo", palette["grip_lo"]))
        elif gtype == "select_arrow":
            zone_px = T.px(glyph["arrow_zone_pts"], density)
            img = T.add_select_arrow(
                img, zone_px, gcolor, outline, pal["border"],
                arrow_w_px=T.px(glyph["arrow_w_pts"], density) if "arrow_w_pts" in glyph else None,
                arrow_h_px=T.px(glyph["arrow_h_pts"], density) if "arrow_h_pts" in glyph else None)
    return img


def render_single_panel(spec, palette, w_px, h_px, density):
    recipe = spec["recipe"]
    radius_px = T.px(spec.get("radius_pts", 0), density)
    # border_pts: 0 drops the outline entirely (the gradient then fills the
    # whole block), which with radius_pts: 0 gives the same surface as its
    # bevelled sibling but with no edge or corners.
    border_px = (max(T.px(spec["border_pts"], density), 0) if "border_pts" in spec
                 else max(T.px(1.2, density), 1))
    if recipe == "recessed_diagonal_panel":
        pal = palette[spec.get("palette", "recessed")]
        return T.recessed_diagonal(w_px, h_px, radius_px, pal["dark"], pal["light"], pal["border"],
                                   border=border_px)
    elif recipe == "flat_bevel_panel":
        pal = palette[spec.get("palette", "panel")]
        return T.flat_bevel_panel(w_px, h_px, radius_px, pal["top"], pal["bottom"], pal["border"],
                                  border=border_px, ease=spec.get("gradient_ease", 1.0))
    raise ValueError(f"Unknown single-block recipe: {recipe}")


def render_widget(name, spec, palette, density):
    w_pts, h_pts = spec["size_pts"]
    w_px, h_px = T.px(w_pts, density), T.px(h_pts, density)
    axis = spec.get("axis", "single")
    spacing_pts = spec.get("spacing_pts", 0)
    spacing_px = T.px(spacing_pts, density)
    states = spec.get("states", ["Default"])

    blocks = []
    for state in states:
        if spec["recipe"] == "raised_control":
            blocks.append(render_state_block(spec, palette, state, w_px, h_px, density))
        else:
            blocks.append(render_single_panel(spec, palette, w_px, h_px, density))

    n = len(blocks)
    if axis == "x":
        strip_w = n * w_px + (n - 1) * spacing_px
        strip = Image.new("RGBA", (strip_w, h_px), (0, 0, 0, 0))
        for i, b in enumerate(blocks):
            strip.alpha_composite(b, (i * (w_px + spacing_px), 0))
    elif axis == "y":
        strip_h = n * h_px + (n - 1) * spacing_px
        strip = Image.new("RGBA", (w_px, strip_h), (0, 0, 0, 0))
        for i, b in enumerate(blocks):
            strip.alpha_composite(b, (0, i * (h_px + spacing_px)))
    else:
        strip = blocks[0]

    meta = {
        "name": name,
        "axis": axis,
        "spacing_pts": spacing_pts,
        "size_pts": [w_pts, h_pts],
        "states": states,
        "frame_pts": spec.get("frame_pts"),
        "padding_pts": spec.get("padding_pts"),
        "rigid_part": spec.get("rigid_part"),
        "stretch_axis": spec.get("stretch_axis"),
        "density": density,
    }
    return strip, meta


# ---------------------------------------------------------------------------
# render subcommand
# ---------------------------------------------------------------------------
def cmd_render(kit, names, force, density):
    kit_dir = KIT_ROOT / kit
    palette = yaml.safe_load((kit_dir / "palette.yaml").read_text())
    specs_dir = kit_dir / "specs"
    parts_dir = kit_dir / "parts"
    parts_dir.mkdir(exist_ok=True)

    all_specs = {p.stem: yaml.safe_load(p.read_text()) for p in sorted(specs_dir.glob("*.yaml"))}

    if names:
        missing = [n for n in names if n not in all_specs]
        if missing:
            raise SystemExit(f"No spec for: {', '.join(missing)}")
        targets = names
    else:
        # No names given: default target set is every spec. --force here means
        # "regenerate everything"; without it, only widgets missing a part are touched.
        targets = list(all_specs)

    skipped = []
    rendered = []
    for name in targets:
        png_path = parts_dir / f"{name}.png"
        if png_path.exists() and not force:
            skipped.append(name)
            continue
        spec = all_specs[name]
        img, meta = render_widget(name, spec, palette, density)
        img.save(png_path)
        (parts_dir / f"{name}.json").write_text(json.dumps(meta, indent=2))
        rendered.append(name)

    print(f"Rendered: {', '.join(rendered) if rendered else '(none)'}")
    if skipped:
        print(f"Skipped (already exist, use --force to overwrite): {', '.join(skipped)}")


# ---------------------------------------------------------------------------
# pack subcommand
# ---------------------------------------------------------------------------
def border_tuple(v):
    """Normalize a frame/padding value (int, or [t,r,b,l]) to a 4-tuple, or None."""
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return (v, v, v, v)
    return tuple(v)


def pack_atlas(kit):
    kit_dir = KIT_ROOT / kit
    parts_dir = kit_dir / "parts"
    parts = []
    for json_path in sorted(parts_dir.glob("*.json")):
        meta = json.loads(json_path.read_text())
        png_path = parts_dir / f"{meta['name']}.png"
        img = Image.open(png_path)
        parts.append((meta, img))

    if not parts:
        raise SystemExit("No parts/ found -- run `render` first.")

    # A part whose spec is gone still gets packed and still generates its
    # Skins:: entry, so deleting only the spec leaves a stale skin in the
    # header that refers to a member nobody declares any more. Hand-authored
    # parts with no spec are legitimate, so warn rather than fail.
    spec_names = {p.stem for p in (kit_dir / "specs").glob("*.yaml")}
    orphans = [m["name"] for m, _ in parts if m["name"] not in spec_names]
    if orphans:
        print(f"warning: parts with no spec in specs/: {', '.join(sorted(orphans))}\n"
              f"         they are still packed and still generate Skins:: entries -- "
              f"delete parts/<name>.png and .json if that is not what you want.",
              file=sys.stderr)

    density = parts[0][0]["density"]
    for meta, _ in parts:
        if meta["density"] != density:
            raise SystemExit(f"Density mismatch: {meta['name']} was rendered at {meta['density']}x, "
                              f"expected {density}x. Re-render everything at one consistent density.")

    ATLAS_WIDTH = 640
    GUTTER = T.px(1, density)
    cursor_x, row_y, row_h = GUTTER, GUTTER, 0
    positions = []

    for meta, img in parts:
        w, h = img.size
        if cursor_x + w + GUTTER > ATLAS_WIDTH:
            row_y += row_h + GUTTER
            cursor_x = GUTTER
            row_h = 0
        positions.append((cursor_x, row_y))
        cursor_x += w + GUTTER
        row_h = max(row_h, h)

    atlas_h = row_y + row_h + GUTTER
    atlas = Image.new("RGBA", (ATLAS_WIDTH, atlas_h), (0, 0, 0, 0))
    manifest = []
    for (meta, img), (x, y) in zip(parts, positions):
        atlas.alpha_composite(img, (x, y))
        manifest.append(dict(meta, atlas_x_pts=round(x / density), atlas_y_pts=round(y / density)))

    return atlas, manifest, density


# Widgets whose skin pointer isn't Skins::<Name> -- everything else defaults to that.
CPP_TARGET_OVERRIDES = {
    "PlusMinusToggle": "_pPlusMinusToggleSkin",
}


def fmt_border(v):
    if v is None:
        return None
    t, r, b, l = border_tuple(v)
    if t == r == b == l:
        return str(int(t))
    return f"{{ {int(t)},{int(r)},{int(b)},{int(l)} }}"


AXIS_CPP = {"x": "Axis::X", "y": "Axis::Y"}


def gen_skin_block(entry):
    target = CPP_TARGET_OVERRIDES.get(entry["name"], f"Skins::{entry['name']}")
    x, y = entry["atlas_x_pts"], entry["atlas_y_pts"]
    w, h = entry["size_pts"]
    lines = [f"\t\t{target} = BlockSkin::create(WGBP(BlockSkin,",
             f"\t\t\t_.surface = pSkinBlocks,",
             f"\t\t\t_.firstBlock = {{ {int(x)},{int(y)},{int(w)},{int(h)} }},"]

    if entry["axis"] in ("x", "y"):
        lines.append(f"\t\t\t_.axis = {AXIS_CPP[entry['axis']]},")
        lines.append(f"\t\t\t_.blockSpacing = {int(entry['spacing_pts'])},")

    frame = fmt_border(entry["frame_pts"])
    if frame is not None:
        lines.append(f"\t\t\t_.frame = {frame},")
    padding = fmt_border(entry["padding_pts"])
    if padding is not None:
        lines.append(f"\t\t\t_.padding = {padding},")

    for rp in rigid_parts(entry):
        field = "rigidPartX" if rp["axis"] == "x" else "rigidPartY"
        enum = "YSections" if rp["axis"] == "x" else "XSections"
        # `sections` may name several, e.g. "Top|Bottom". Qualify each one:
        # "YSections::Top|Bottom" is not valid C++, and both enums define
        # operator| (plus an All) in wg_gfxtypes.h.
        sections = " | ".join(f"{enum}::{s.strip()}" for s in str(rp["sections"]).split("|"))
        lines.append(f"\t\t\t_.{field} = {{{int(rp['begin_pts'])},{int(rp['length_pts'])},{sections}}},")

    states = entry["states"]
    if not (len(states) == 1 and states[0] == "Default"):
        states_cpp = ", ".join(f"State::{s}" for s in states)
        lines.append(f"\t\t\t_.states = {{ {states_cpp} }}")
    else:
        lines[-1] = lines[-1].rstrip(",")  # drop trailing comma on last real field

    # Clean up: ensure no trailing comma before closing paren
    if lines[-1].endswith(","):
        lines[-1] = lines[-1][:-1]

    lines.append("\t\t));")
    return "\n".join(lines)


BEGIN_MARKER = "// >>> BEGIN GENERATED SKINS <<<"
END_MARKER = "// >>> END GENERATED SKINS <<<"

COLORS_BEGIN = "// >>> BEGIN GENERATED COLORS <<<"
COLORS_END = "// >>> END GENERATED COLORS <<<"


def _marker_line_matches(marker, shell):
    """Find occurrences of `marker` appearing as its OWN line (only leading/
    trailing whitespace beside it). A plain substring search is not safe here:
    if any hand-written prose elsewhere in header_shell.h happens to mention
    the marker text (e.g. explaining what the markers do), a naive
    str.split() would silently splice at the wrong spot instead of the real
    marker, quietly discarding everything in between. Returns a list of
    re.Match objects, in order."""
    pattern = re.compile(r"^[ \t]*" + re.escape(marker) + r"[ \t]*$", re.MULTILINE)
    return list(pattern.finditer(shell))


def gen_colors(kit, palette, density):
    """Emit the Colors:: constants declared under `exported_colors` in
    palette.yaml.

    These were hand-written C++ while the gradients lived in YAML, with
    nothing tying the two together -- so every palette change silently
    invalidated them, and Colors::Plate drifted to the gradient's TOP colour
    while the bitmap's middle was 14 levels darker. Anything using it to sit
    flush against a Plate was visibly off.

    `center_of` is the important form: it MEASURES the centre pixel of a
    rendered part, so the constant is whatever the bitmap actually is, however
    the recipe draws it. The others are conveniences for colours a bitmap
    doesn't define.
    """
    parts_dir = KIT_ROOT / kit / "parts"
    lines = []
    for name, src in (palette.get("exported_colors") or {}).items():
        if "center_of" in src:
            part = src["center_of"]
            meta = json.loads((parts_dir / f"{part}.json").read_text())
            img = Image.open(parts_dir / f"{part}.png").convert("RGBA")
            d = meta.get("density", density)
            w, h = (round(v * d) for v in meta["size_pts"])
            rgb = img.crop((0, 0, w, h)).getpixel((w // 2, h // 2))[:3]
            auto = f"measured: centre pixel of parts/{part}.png"
        elif "border_of" in src:
            rgb = tuple(palette[src["border_of"]]["border"][:3])
            auto = f"palette: {src['border_of']}.border"
        elif "top_of" in src or "bottom_of" in src:
            key = "top_of" if "top_of" in src else "bottom_of"
            rgb = tuple(palette[src[key]][key[:-3]][:3])
            auto = f"palette: {src[key]}.{key[:-3]}"
        elif "rgb" in src:
            rgb = tuple(src["rgb"])
            auto = ""
        else:
            raise SystemExit(f"exported_colors[{name}]: need one of "
                             f"center_of / border_of / top_of / bottom_of / rgb")
        note = src.get("note", auto)
        if src.get("comment"):
            if lines:
                lines.append("")
            for cl in src["comment"].rstrip("\n").split("\n"):
                lines.append(f"\t\t// {cl}".rstrip())
        decl = f"\t\tinline const Color\t{name} = Color({rgb[0]},{rgb[1]},{rgb[2]});"
        lines.append(f"{decl}\t\t// {note}" if note else decl)
    return "\n".join(lines)


def _splice(shell, begin, end, body):
    """Replace the region between the `begin` and `end` marker lines with
    `body`, keeping the marker lines themselves."""
    begin_matches = _marker_line_matches(begin, shell)
    end_matches = _marker_line_matches(end, shell)

    if len(begin_matches) != 1 or len(end_matches) != 1:
        raise SystemExit(
            f"header_shell.h must contain exactly one {begin!r} line "
            f"and one {end!r} line (found {len(begin_matches)} / "
            f"{len(end_matches)}). If these strings appear elsewhere too "
            f"(e.g. in an explanatory comment), reword that mention so it "
            f"isn't a standalone line matching the marker exactly."
        )
    if begin_matches[0].start() >= end_matches[0].start():
        raise SystemExit(f"header_shell.h: {begin!r} must come before {end!r}")

    # post starts at the END marker's own line start (the match includes that
    # line's leading whitespace), so its original indentation is preserved and
    # nothing is added in front of it.
    pre = shell[: begin_matches[0].end()]
    post = shell[end_matches[0].start() :]
    return f"{pre}\n{body}\n{post}"


def generate_header(kit, manifest, palette, density):
    kit_dir = KIT_ROOT / kit
    shell = (kit_dir / "header_shell.h").read_text()

    shell = _splice(shell, COLORS_BEGIN, COLORS_END, gen_colors(kit, palette, density))
    shell = _splice(shell, BEGIN_MARKER, END_MARKER,
                    "\n\n".join(gen_skin_block(e) for e in manifest))
    return shell


# ---------------------------------------------------------------------------
# Faithful port of GfxDeviceGen1::blitNinePatch, used to render the preview's
# stretch demos. CSS border-image cannot express rigidPartX/Y at all, so
# simulating the real algorithm here is the only way the preview can show what
# the widget will actually look like when stretched.
# ---------------------------------------------------------------------------
def rigid_parts(entry):
    """A spec's rigid parts as a list. `rigid_part` may be a single mapping or
    a list of them -- a block can pin BOTH axes at once (BlockSkin has separate
    rigidPartX and rigidPartY fields, and blitNinePatch nests them: it splits
    the centre cell by rigidPartY, then applies rigidPartX within each of the
    resulting bands). A bar that is stretched along its length but may also be
    drawn at a different thickness needs both, or the glyph smears on the axis
    that was left unpinned."""
    rp = entry.get("rigid_part")
    if not rp:
        return []
    return list(rp) if isinstance(rp, list) else [rp]


def rebase_rigid(rp, frame_px, block_size, density):
    """Convert a spec rigid_part into middle-band-relative pixels.

    BlockSkin stores `begin` in BLOCK coordinates then rebases it onto the
    stretchable middle band (`ofs -= frame.top`, clamped to the band), so we
    do exactly the same to stay in step with it.
    """
    t, r, b, l = frame_px
    sw, sh = block_size
    ofs = round(rp["begin_pts"] * density)
    length = round(rp["length_pts"] * density)
    if rp["axis"] == "y":
        mid, ofs = sh - t - b, ofs - t
    else:
        mid, ofs = sw - l - r, ofs - l
    if ofs < 0:
        length, ofs = length + ofs, 0
    if ofs + length > mid:
        length = mid - ofs
    # rigidPartX is masked by YSections (rows), rigidPartY by XSections (cols).
    names = {s.strip() for s in str(rp["sections"]).split("|")}
    if "All" in names:
        names = {"Top", "Center", "Bottom"} if rp["axis"] == "x" else {"Left", "Center", "Right"}
    return dict(axis=rp["axis"], ofs=ofs, len=max(length, 0), sections=names)


def rigid_spans(src_len, dst_len, ofs, length):
    """Split one stretchable band into (src_ofs, src_len, dst_len) runs.

    Mirrors the arithmetic in blitNinePatch: the rigid run keeps its natural
    length and whatever destination space is left over is divided between the
    two flanks in proportion to their SOURCE lengths. Note the guard -- the
    engine divides by (lead+trail), so a rigid run covering the whole band
    would divide by zero there; we degrade to a plain stretch instead.
    """
    lead_src, trail_src = ofs, src_len - ofs - length
    total_src = lead_src + trail_src
    if total_src <= 0 or length <= 0:
        return [(0, src_len, dst_len)]
    mid_dst = min(length, dst_len)
    lead_dst = (dst_len - mid_dst) * lead_src // total_src
    trail_dst = dst_len - mid_dst - lead_dst
    return [(0, lead_src, lead_dst),
            (lead_src, length, mid_dst),
            (lead_src + length, trail_src, trail_dst)]


def simulate_stretch(block, frame_px, target_px, rigids=()):
    """Stretch a single state block to `target_px` the way WonderGUI would.

    Source and destination share a px-per-pt density here, so the frame keeps
    its pixel size and only the middle bands scale.
    """
    t, r, b, l = frame_px
    sw, sh = block.size
    tw, th = target_px
    out = Image.new("RGBA", (tw, th), (0, 0, 0, 0))

    cols = [(0, l, 0, l, "Left"),
            (l, sw - l - r, l, tw - l - r, "Center"),
            (sw - r, r, tw - r, r, "Right")]
    rows = [(0, t, 0, t, "Top"),
            (t, sh - t - b, t, th - t - b, "Center"),
            (sh - b, b, th - b, b, "Bottom")]

    rx = next((r for r in rigids if r["axis"] == "x"), None)
    ry = next((r for r in rigids if r["axis"] == "y"), None)

    for sx, swid, dx, dwid, cname in cols:
        if swid <= 0 or dwid <= 0:
            continue
        for sy, shgt, dy, dhgt, rname in rows:
            if shgt <= 0 or dhgt <= 0:
                continue
            # rigidPartY subdivides the vertical middle of the named X sections
            vspans = (rigid_spans(shgt, dhgt, ry["ofs"], ry["len"])
                      if ry and rname == "Center" and cname in ry["sections"]
                      else [(0, shgt, dhgt)])
            # rigidPartX subdivides the horizontal middle of the named Y sections
            hspans = (rigid_spans(swid, dwid, rx["ofs"], rx["len"])
                      if rx and cname == "Center" and rname in rx["sections"]
                      else [(0, swid, dwid)])
            dyy = dy
            for vso, vsl, vdl in vspans:
                dxx = dx
                for hso, hsl, hdl in hspans:
                    if hsl > 0 and vsl > 0 and hdl > 0 and vdl > 0:
                        piece = block.crop((sx + hso, sy + vso,
                                            sx + hso + hsl, sy + vso + vsl))
                        if (hdl, vdl) != (hsl, vsl):
                            piece = piece.resize((hdl, vdl), Image.BILINEAR)
                        out.paste(piece, (dxx, dyy))
                    dxx += hdl
                dyy += vdl
    return out


# ---------------------------------------------------------------------------
# preview.html: contact sheet + simulated stretch check
# ---------------------------------------------------------------------------
def build_preview_html(kit, atlas, manifest, density):
    import base64
    import io

    def b64_crop(meta):
        x, y = round(meta["atlas_x_pts"] * density), round(meta["atlas_y_pts"] * density)
        w, h = round(meta["size_pts"][0] * density), round(meta["size_pts"][1] * density)
        n = len(meta["states"])
        if meta["axis"] == "x":
            full = atlas.crop((x, y, x + n * w + (n - 1) * round(meta["spacing_pts"] * density), y + h))
        elif meta["axis"] == "y":
            full = atlas.crop((x, y, x + w, y + n * h + (n - 1) * round(meta["spacing_pts"] * density)))
        else:
            full = atlas.crop((x, y, x + w, y + h))
        buf = io.BytesIO()
        full.save(buf, "PNG")
        return base64.b64encode(buf.getvalue()).decode()

    css = """
    body{font-family:sans-serif;background:#eef0f3;padding:20px;color:#222}
    h2{font-size:13px;margin:22px 0 6px}
    .meta{font-size:11px;color:#667;margin-bottom:6px}
    .ok{color:#186a3b}
    .row{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin-bottom:8px}
    .chip{image-rendering:pixelated;border:1px solid #ccc;background:
      repeating-conic-gradient(#ddd 0% 25%, #fff 0% 50%) 50% / 12px 12px}
    .demo{position:relative}
    .demo img{display:block;width:100%;height:100%;image-rendering:pixelated}
    .content{position:absolute;display:flex;align-items:center;justify-content:flex-start;
      outline:1px dashed rgba(0,0,0,.35);color:#08306b;font-weight:600;font-size:12px}
    """
    html = [f'<!doctype html><html><head><meta charset="utf-8"><title>{kit} preview</title><style>{css}</style></head><body>']
    html.append(f"<h1>{kit} widgetkit preview</h1>")

    zoom = 4          # CSS px per pt in this preview

    for meta in manifest:
        b64 = b64_crop(meta)
        name = meta["name"]
        html.append(f"<h2>{name}</h2>")
        rigid_note = ""
        for rp in rigid_parts(meta):
            rigid_note += (f" &middot; <span class='ok'>rigidPart{rp['axis'].upper()} "
                           f"{rp['begin_pts']}..{rp['begin_pts'] + rp['length_pts']}pts "
                           f"({rp['sections']}) held rigid below</span>")
        html.append(f"<div class='meta'>states: {', '.join(meta['states'])} &middot; "
                     f"size_pts: {meta['size_pts']} &middot; frame_pts: {meta['frame_pts']} &middot; "
                     f"padding_pts: {meta['padding_pts']}{rigid_note}</div>")
        html.append("<div class='row'>")
        html.append(f"<img class='chip' style='width:auto;height:{meta['size_pts'][1]*zoom if meta['axis']!='y' else meta['size_pts'][1]*len(meta['states'])*zoom}px' "
                     f"src='data:image/png;base64,{b64}'>")

        # Any framed block gets stretch demos, including single-state panels
        # (axis "single"). Those were excluded before, which is precisely why
        # Plate/Canvas/Window went so long with no frame at all: the preview
        # never showed them stretched, so the smeared borders never appeared.
        if meta["frame_pts"] is not None:
            t, r, b, l = border_tuple(meta["frame_pts"])
            w_pts, h_pts = meta["size_pts"]
            frame_px = tuple(round(v * density) for v in (t, r, b, l))

            block = atlas.crop((round(meta["atlas_x_pts"] * density),
                                round(meta["atlas_y_pts"] * density),
                                round((meta["atlas_x_pts"] + w_pts) * density),
                                round((meta["atlas_y_pts"] + h_pts) * density)))
            rigids = [rebase_rigid(rp, frame_px, block.size, density)
                      for rp in rigid_parts(meta)]

            # Only demo an axis that has stretchable material left over. A
            # horizontal scrollbar handle's frame spans its full height by
            # design (top 8 + bottom 8 of a 16pt block), so a "taller" demo
            # would show a legitimately empty band and read as a defect.
            stretch_x, stretch_y = (l + r) < w_pts, (t + b) < h_pts
            if stretch_x and stretch_y:
                # First demo shows the widget stretched along the axis it is
                # actually used on, so it reads as normal usage; the second
                # stretches both, to stress the other axis and any rigid part
                # pinned on it. A split bar grows along its length only, so
                # showing it 2x WIDE first was misleading.
                primary = meta.get("stretch_axis") or "x"
                if primary == "y":
                    sizes = [(w_pts, h_pts * 2), (w_pts * 2, h_pts * 3)]
                else:
                    sizes = [(w_pts * 2, h_pts), (w_pts * 3, h_pts * 2)]
            elif stretch_x:
                sizes = [(w_pts * 2, h_pts), (w_pts * 4, h_pts)]
            elif stretch_y:
                sizes = [(w_pts, h_pts * 2), (w_pts, h_pts * 4)]
            else:
                sizes = []

            pt, pr, pb, pl = border_tuple(meta["padding_pts"]) or (0, 0, 0, 0)
            for w, h in sizes:
                img = simulate_stretch(block, frame_px,
                                       (round(w * density), round(h * density)), rigids)
                buf = io.BytesIO()
                img.save(buf, "PNG")
                d64 = base64.b64encode(buf.getvalue()).decode()
                # The dashed box is the content rect (size minus padding) --
                # it shows at a glance whether text would collide with an
                # inset glyph such as the select box's arrow.
                html.append(
                    f"<div class='demo' style='width:{w*zoom}px;height:{h*zoom}px' "
                    f"title='{name} stretched to {w}x{h} pts'>"
                    f"<img src='data:image/png;base64,{d64}'>"
                    f"<div class='content' style='top:{pt*zoom}px;right:{pr*zoom}px;"
                    f"bottom:{pb*zoom}px;left:{pl*zoom}px'>Aa</div></div>")
        html.append("</div>")

    html.append("</body></html>")
    return "\n".join(html)


# ---------------------------------------------------------------------------
def cmd_pack(kit):
    atlas, manifest, density = pack_atlas(kit)
    kit_dir = KIT_ROOT / kit

    atlas_name = f"{kit}_skinblocks.png"
    header_name = f"wg_{kit}.h"

    atlas.save(kit_dir / atlas_name)
    palette = yaml.safe_load((kit_dir / "palette.yaml").read_text())
    (kit_dir / header_name).write_text(generate_header(kit, manifest, palette, density))
    (kit_dir / "preview.html").write_text(build_preview_html(kit, atlas, manifest, density))

    (REPO_ROOT / "resources").mkdir(parents=True, exist_ok=True)
    (REPO_ROOT / "src" / "widgetkits").mkdir(parents=True, exist_ok=True)
    atlas.save(REPO_ROOT / "resources" / atlas_name)
    (REPO_ROOT / "src" / "widgetkits" / header_name).write_text((kit_dir / header_name).read_text())

    print(f"Packed {len(manifest)} widgets into {atlas.size[0]}x{atlas.size[1]} atlas @ {density}x density")
    print(f"Wrote {kit_dir / atlas_name}, {kit_dir / header_name}, {kit_dir / 'preview.html'}")
    print(f"Deployed to resources/{atlas_name} and src/widgetkits/{header_name}")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    r = sub.add_parser("render")
    r.add_argument("kit")
    r.add_argument("names", nargs="*")
    r.add_argument("--force", action="store_true")
    r.add_argument("--density", type=float, default=DEFAULT_DENSITY)

    p = sub.add_parser("pack")
    p.add_argument("kit")

    args = ap.parse_args()
    if args.cmd == "render":
        cmd_render(args.kit, args.names, args.force, args.density)
    elif args.cmd == "pack":
        cmd_pack(args.kit)


if __name__ == "__main__":
    main()
