#!/usr/bin/env python3
"""
widgetkit-src build tool.

Usage:
  python3 build.py render <kit> [widget ...] [--force]
      Render specs/*.yaml (or just the named widgets) into parts/<name>.png
      + parts/<name>.json. Only touches widgets you name, or ones with no
      parts/ file yet -- pass --force to also overwrite named widgets that
      already have rendered parts.

  python3 build.py pack <kit>
      Read every parts/*.png + .json pair, pack them into the atlas,
      regenerate the header's two generated sections (the Colors:: constants,
      from palette.yaml's exported_colors, and the Skins::), rebuild
      preview.html, and copy the atlas + header to their real repo
      locations (resources/, src/widgetkits/).

Directory layout expected (kit_dir = widgetkit-src/<kit>/):
  palette.yaml
  specs/<Name>.yaml
  parts/<Name>.png, parts/<Name>.json      (generated by `render`)
  header_shell.h                            (hand-maintained)
  preview.html, <kit>_skinblocks.png, wg_<kit>.h   (generated by `pack`)
"""
import argparse
import json
import math
import re
import sys
from pathlib import Path

import yaml
from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).parent))
import theme_lib as T

REPO_ROOT = Path(__file__).resolve().parents[2]
KIT_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_DENSITY = 2

# Render styling per State name: which palette entry to use, how much gloss,
# how much inward "pressed" shading, and overall opacity. This table is
# rendering logic (a "recipe" concern), not per-kit data, so it lives in code.
STATE_STYLE = {
    "Default":         dict(pal="raised",        gloss=150, inset=0,  alpha=1.0),
    "Hovered":         dict(pal="hover",          gloss=185, inset=0,  alpha=1.0),
    "Pressed":         dict(pal="pressed",        gloss=40,  inset=70, alpha=1.0),
    "Disabled":        dict(pal="disabled",       gloss=25,  inset=0,  alpha=0.82),
    "Checked":         dict(pal="checked",        gloss=60,  inset=55, alpha=1.0),
    "CheckedHovered":  dict(pal="checked_hover",  gloss=90,  inset=35, alpha=1.0),
    "CheckedPressed":  dict(pal="pressed",        gloss=25,  inset=95, alpha=1.0),
    "DisabledChecked": dict(pal="disabled",       gloss=15,  inset=40, alpha=0.82),
}


def glyph_color(palette, state):
    return palette["glyph_disabled"] if state.startswith("Disabled") else palette["glyph_white"]


def is_checked(state):
    """Does this state show the widget's "on" glyph?

    Substring, not startswith: the checked family is Checked / CheckedHovered /
    CheckedPressed *and* DisabledChecked, and that last one does not start with
    "Checked". A startswith test silently drops the tick from a disabled ticked
    box.
    """
    return "Checked" in state


def render_state_block(spec, palette, state, w_px, h_px, density):
    radius_px = T.px(spec.get("radius_pts", 0), density)
    shape = spec.get("shape", "rect")
    border_px = max(T.px(1.2, density), 1)

    # `state_style_as` renders one state with another's STATE_STYLE entry. A
    # checkbox wants its background to say hovered/pressed and nothing else --
    # ticking it must not also recolour it, or the tick and the surface are
    # both saying "on" and neither is left to say what the pointer is doing.
    # So Checked is drawn exactly like Default, CheckedHovered like Hovered,
    # and the only difference between the two families is the glyph. The glyph
    # still follows the real state.
    style_state = (spec.get("state_style_as") or {}).get(state, state)
    style = STATE_STYLE[style_state]
    # STATE_STYLE names a palette entry per state ("raised", "hover", ...).
    # `palette_family` prefixes those, so a kit can carry more than one family
    # of control colours -- e.g. `plate` for controls that should read as
    # furniture rather than accents -- without duplicating the state table.
    family = spec.get("palette_family")
    pal = palette[f"{family}_{style['pal']}" if family else style["pal"]]
    img = T.raised_panel(w_px, h_px, radius_px, pal, border=border_px,
                          gloss_alpha=style["gloss"], shape=shape,
                          gloss_frac=spec.get("gloss_frac", 0.5),
                          ease=spec.get("gradient_ease", 1.0))
    if style["inset"] > 0:
        img = T.inset_shade(img, w_px, h_px, radius_px, amount=style["inset"], shape=shape, border=border_px)
    if style["alpha"] < 1.0:
        r, g, b, a = img.split()
        a = a.point(lambda v: int(v * style["alpha"]))
        img = Image.merge("RGBA", (r, g, b, a))

    glyph = spec.get("glyph")
    if glyph:
        shift = (spec.get("glyph_shift") or {}).get(state)
        if shift:
            # Draw the glyph on its own transparent layer and paste it offset.
            # This is the bitmap equivalent of BlockSkin's contentShift, for a
            # glyph that lives in the ARTWORK rather than being widget content:
            # a checkbox's tick is drawn into the block, and Skins::Checkbox is
            # an icon skin whose content is nothing, so nothing at runtime can
            # move it.
            #
            # Unshifted glyphs keep drawing straight onto the panel. Routing
            # those through a layer too would be the same picture in theory,
            # but PIL composites in 8-bit and A-over-(B-over-C) can round a
            # level differently from (A-over-B)-over-C -- which would rewrite
            # every part in the atlas for no visible gain.
            layer = _draw_glyph(Image.new("RGBA", img.size, (0, 0, 0, 0)),
                                glyph, palette, pal, state, w_px, h_px, density)
            img.alpha_composite(layer, (T.px(shift[0], density), T.px(shift[1], density)))
            return img
        return _draw_glyph(img, glyph, palette, pal, state, w_px, h_px, density)
    return img


def _draw_glyph(img, glyph, palette, pal, state, w_px, h_px, density):
    """Composite a glyph onto `img`. Split out of render_state_block so the
    same drawing can go either straight onto the panel or onto a transparent
    layer that is then pasted at an offset."""
    gtype = glyph["type"]
    gcolor = glyph_color(palette, state)
    outline = palette["glyph_outline"]
    if gtype == "arrow":
        # Default proportions match the select box's arrow (base twice the
        # base-to-tip depth), transposed for the horizontal directions.
        dw, dh = (10, 5) if glyph["direction"] in ("up", "down") else (5, 10)
        img = T.add_arrow_glyph(img, glyph["direction"], gcolor, outline,
                                T.px(glyph.get("arrow_w_pts", dw), density),
                                T.px(glyph.get("arrow_h_pts", dh), density))
    elif gtype == "plusminus":
        mode = "minus" if is_checked(state) else "plus"
        img = T.add_plusminus_glyph(img, mode, gcolor)
    elif gtype == "check":
        if is_checked(state):
            img = T.add_check_glyph(
                img, gcolor,
                check_w_px=T.px(glyph["check_w_pts"], density) if "check_w_pts" in glyph else None,
                check_h_px=T.px(glyph["check_h_pts"], density) if "check_h_pts" in glyph else None,
                stroke_px=T.px(glyph["stroke_pts"], density) if "stroke_pts" in glyph else None,
                outline=outline if glyph.get("outline", False) else None)
    elif gtype == "dot":
        if is_checked(state):
            img = T.add_dot_glyph(
                img, gcolor,
                dot_px=T.px(glyph["dot_pts"], density) if "dot_pts" in glyph else None,
                outline=outline if glyph.get("outline", False) else None)
    elif gtype == "grip":
        # Ridges run ACROSS the axis the handle is dragged along, so a wide
        # handle gets vertical lines -- the opposite of what the block's
        # aspect ratio suggests, which is how this got reversed before.
        # Stated per-spec; the fallback follows the same rule.
        direction = glyph.get("direction") or ("vertical" if w_px >= h_px else "horizontal")
        img = T.add_grip_lines(img, f"{direction}_lines", palette["grip_hi"], palette["grip_lo"],
                               T.px(glyph["len_pts"], density) if "len_pts" in glyph else None)
    elif gtype == "dotgrid":
        img = T.add_dot_grid(img, palette["grip_hi"], palette["grip_lo"])
    elif gtype == "dots":
        # Dots line up ALONG the bar, which is the split panel convention
        # (unlike scrollbar grip ridges, which run across the drag axis).
        img = T.add_dot_line(img, glyph["direction"], glyph.get("count", 3),
                             T.px(glyph.get("dot_pts", 2.5), density),
                             T.px(glyph.get("gap_pts", 4), density),
                             palette.get("dot_hi", palette["grip_hi"]),
                             palette.get("dot_lo", palette["grip_lo"]))
    elif gtype == "select_arrow":
        zone_px = T.px(glyph["arrow_zone_pts"], density)
        img = T.add_select_arrow(
            img, zone_px, gcolor, outline, pal["border"],
            arrow_w_px=T.px(glyph["arrow_w_pts"], density) if "arrow_w_pts" in glyph else None,
            arrow_h_px=T.px(glyph["arrow_h_pts"], density) if "arrow_h_pts" in glyph else None)
    return img


def render_dot_overlay(spec, palette, state, w_px, h_px, density):
    """A fully transparent block carrying nothing but the engraved dot run.

    This is the front layer of a DoubleSkin whose back layer is the plain grey
    bar. Splitting them is what lets the dots grow: on a single block the dots
    had to fit inside a rigid part carved out of the bar's own middle band, and
    that band is only as wide as the bar minus its frame -- on an 8pt bar,
    4pts, which caps the dots at about 2pts. The overlay has no border and no
    corners, so it needs no frame at all: the whole block is the centre section
    and the rigid part can be almost as wide as the bar.

    Only the per-state ALPHA from STATE_STYLE is applied (so the dots fade with
    a disabled bar); colour, gloss and inset shading all belong to the layer
    underneath.
    """
    glyph = spec["glyph"]
    img = Image.new("RGBA", (w_px, h_px), (0, 0, 0, 0))
    img = T.add_dot_line(img, glyph["direction"], glyph.get("count", 3),
                         T.px(glyph.get("dot_pts", 2.5), density),
                         T.px(glyph.get("gap_pts", 4), density),
                         palette.get("dot_hi", palette["grip_hi"]),
                         palette.get("dot_lo", palette["grip_lo"]))
    alpha = STATE_STYLE[state]["alpha"]
    if alpha < 1.0:
        r, g, b, a = img.split()
        img = Image.merge("RGBA", (r, g, b, a.point(lambda v: int(v * alpha))))
    return img


def render_single_panel(spec, palette, w_px, h_px, density):
    recipe = spec["recipe"]
    radius_px = T.px(spec.get("radius_pts", 0), density)
    # border_pts: 0 drops the outline entirely (the gradient then fills the
    # whole block), which with radius_pts: 0 gives the same surface as its
    # bevelled sibling but with no edge or corners.
    border_px = (max(T.px(spec["border_pts"], density), 0) if "border_pts" in spec
                 else max(T.px(1.2, density), 1))
    if recipe == "recessed_diagonal_panel":
        pal = palette[spec.get("palette", "recessed")]
        return T.recessed_diagonal(w_px, h_px, radius_px, pal["dark"], pal["light"], pal["border"],
                                   border=border_px)
    elif recipe == "flat_bevel_panel":
        pal = palette[spec.get("palette", "panel")]
        return T.flat_bevel_panel(w_px, h_px, radius_px, pal["top"], pal["bottom"], pal["border"],
                                  border=border_px, ease=spec.get("gradient_ease", 1.0))
    raise ValueError(f"Unknown single-block recipe: {recipe}")


def render_widget(name, spec, palette, density):
    w_pts, h_pts = spec["size_pts"]
    w_px, h_px = T.px(w_pts, density), T.px(h_pts, density)
    axis = spec.get("axis", "single")
    # NOTE two different spacings, matching BlockSkin's own two fields:
    #   block_spacing_pts -> _.blockSpacing, the gap between state blocks
    #                        INSIDE the atlas strip. A packing detail.
    #   spacing_pts       -> _.spacing, an outer MARGIN around the whole
    #                        widget, which is what separates it from its
    #                        neighbours in a panel. Nothing to do with the
    #                        bitmap; see the per-spec comments for who gets it.
    block_spacing_pts = spec.get("block_spacing_pts", 0)
    spacing_px = T.px(block_spacing_pts, density)
    states = spec.get("states", ["Default"])

    blocks = []
    for state in states:
        if spec["recipe"] == "raised_control":
            blocks.append(render_state_block(spec, palette, state, w_px, h_px, density))
        elif spec["recipe"] == "dot_overlay":
            blocks.append(render_dot_overlay(spec, palette, state, w_px, h_px, density))
        else:
            blocks.append(render_single_panel(spec, palette, w_px, h_px, density))

    n = len(blocks)
    if axis == "x":
        strip_w = n * w_px + (n - 1) * spacing_px
        strip = Image.new("RGBA", (strip_w, h_px), (0, 0, 0, 0))
        for i, b in enumerate(blocks):
            strip.alpha_composite(b, (i * (w_px + spacing_px), 0))
    elif axis == "y":
        strip_h = n * h_px + (n - 1) * spacing_px
        strip = Image.new("RGBA", (w_px, strip_h), (0, 0, 0, 0))
        for i, b in enumerate(blocks):
            strip.alpha_composite(b, (0, i * (h_px + spacing_px)))
    else:
        strip = blocks[0]

    meta = {
        "name": name,
        "axis": axis,
        "block_spacing_pts": block_spacing_pts,
        "spacing_pts": spec.get("spacing_pts"),
        "size_pts": [w_pts, h_pts],
        "states": states,
        "frame_pts": spec.get("frame_pts"),
        "padding_pts": spec.get("padding_pts"),
        "rigid_part": spec.get("rigid_part"),
        "stretch_axis": spec.get("stretch_axis"),
        "preview_over": spec.get("preview_over"),
        "blocks_from": spec.get("blocks_from"),
        "content_shift": spec.get("content_shift"),
        "density": density,
    }
    return strip, meta


# ---------------------------------------------------------------------------
# render subcommand
# ---------------------------------------------------------------------------
def cmd_render(kit, names, force, density):
    kit_dir = KIT_ROOT / kit
    palette = yaml.safe_load((kit_dir / "palette.yaml").read_text())
    specs_dir = kit_dir / "specs"
    parts_dir = kit_dir / "parts"
    parts_dir.mkdir(exist_ok=True)

    all_specs = {p.stem: yaml.safe_load(p.read_text()) for p in sorted(specs_dir.glob("*.yaml"))}

    if names:
        missing = [n for n in names if n not in all_specs]
        if missing:
            raise SystemExit(f"No spec for: {', '.join(missing)}")
        targets = names
    else:
        # No names given: default target set is every spec. --force here means
        # "regenerate everything"; without it, only widgets missing a part are touched.
        targets = list(all_specs)

    skipped = []
    rendered = []
    for name in targets:
        spec = all_specs[name]

        # `blocks_from: <Other>` means "the same bitmap as <Other>, wrapped in a
        # second skin with its own padding / spacing". It renders no pixels and
        # takes no atlas space: `pack` copies the source's block coordinates.
        # Two skins over one block, rather than two copies of the art that can
        # drift apart -- Skins::Field is Skins::Canvas plus an outer margin, and
        # saying so is clearer than a near-duplicate spec.
        if "blocks_from" in spec:
            src = spec["blocks_from"]
            if src not in all_specs:
                raise SystemExit(f"{name}: blocks_from names {src!r}, which has no spec")
            if "blocks_from" in all_specs[src]:
                raise SystemExit(f"{name}: blocks_from must name a real part, "
                                 f"but {src!r} is itself a blocks_from alias")
            json_path = parts_dir / f"{name}.json"
            if json_path.exists() and not force:
                skipped.append(name)
                continue
            meta = dict(name=name, blocks_from=src, density=density,
                        frame_pts=spec.get("frame_pts"),
                        padding_pts=spec.get("padding_pts"),
                        spacing_pts=spec.get("spacing_pts"),
                        rigid_part=spec.get("rigid_part"),
                        stretch_axis=spec.get("stretch_axis"),
                        preview_over=spec.get("preview_over"),
                        content_shift=spec.get("content_shift"))
            json_path.write_text(json.dumps(meta, indent=2))
            rendered.append(name)
            continue

        png_path = parts_dir / f"{name}.png"
        if png_path.exists() and not force:
            skipped.append(name)
            continue
        img, meta = render_widget(name, spec, palette, density)
        img.save(png_path)
        (parts_dir / f"{name}.json").write_text(json.dumps(meta, indent=2))
        rendered.append(name)

    print(f"Rendered: {', '.join(rendered) if rendered else '(none)'}")
    if skipped:
        print(f"Skipped (already exist, use --force to overwrite): {', '.join(skipped)}")


# ---------------------------------------------------------------------------
# pack subcommand
# ---------------------------------------------------------------------------
def border_tuple(v):
    """Normalize a frame/padding value (int, or [t,r,b,l]) to a 4-tuple, or None."""
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return (v, v, v, v)
    return tuple(v)


# ---------------------------------------------------------------------------
# Atlas packing
#
# A MaxRects packer, plus a search over bin widths and over the packer's own
# tuning knobs. This replaced a shelf packer (fill a row left to right at a
# fixed 640px width, start a new row when the next part does not fit) which
# packed the kit at 27.5% occupancy: the widest part is 358px, so every row
# containing only small parts wasted most of 640px, and the fixed width meant
# a part growing by one pixel could push a whole row down.
#
# Nothing here knows anything about widgets. It takes rectangles and gives
# back positions, so it keeps packing tightly when a part changes size, which
# a hand-tuned layout would not.
# ---------------------------------------------------------------------------

def _rect_contains(outer, inner):
    ox, oy, ow, oh = outer
    ix, iy, iw, ih = inner
    return ix >= ox and iy >= oy and ix + iw <= ox + ow and iy + ih <= oy + oh


def _split_free(free, used):
    """MaxRects' core step: replace every free rectangle that overlaps `used`
    with the (up to four) maximal rectangles of what is left of it, then drop
    any that another one already contains.

    The pruning is what keeps the list from exploding, and it is safe only
    because duplicates are removed first: two identical rectangles each
    contain the other, so without the dedupe both would be dropped.
    """
    ux, uy, uw, uh = used
    out = []
    for f in free:
        fx, fy, fw, fh = f
        if ux >= fx + fw or ux + uw <= fx or uy >= fy + fh or uy + uh <= fy:
            out.append(f)
            continue
        if ux > fx:
            out.append((fx, fy, ux - fx, fh))
        if ux + uw < fx + fw:
            out.append((ux + uw, fy, fx + fw - (ux + uw), fh))
        if uy > fy:
            out.append((fx, fy, fw, uy - fy))
        if uy + uh < fy + fh:
            out.append((fx, uy + uh, fw, fy + fh - (uy + uh)))
    uniq = list(dict.fromkeys(out))
    return [a for i, a in enumerate(uniq)
            if not any(_rect_contains(b, a) for j, b in enumerate(uniq) if j != i)]


# How to score a candidate free rectangle for the piece being placed. Each
# returns a sort key; lowest wins. The trailing (fy, fx) in every key is what
# makes the result deterministic when several spots score the same.
PACK_HEURISTICS = {
    # Best short side fit: leave the smallest sliver on the tighter axis.
    "bssf":  lambda w, h, fx, fy, fw, fh: (min(fw - w, fh - h), max(fw - w, fh - h), fy, fx),
    # Best area fit: waste the least area, tie-broken like bssf.
    "baf":   lambda w, h, fx, fy, fw, fh: (fw * fh - w * h, min(fw - w, fh - h), fy, fx),
    # Bottom left: keep the skyline as low as possible.
    "bl":    lambda w, h, fx, fy, fw, fh: (fy + h, fx, fy),
}

# The order pieces are offered in. Big-first is the usual rule, but which
# measure of "big" wins depends on the shape mix, so all of them are tried.
PACK_ORDERS = {
    "maxside": lambda s, i: (-max(s), -s[0] * s[1], i),
    "area":    lambda s, i: (-s[0] * s[1], -max(s), i),
    "height":  lambda s, i: (-s[1], -s[0], i),
    "width":   lambda s, i: (-s[0], -s[1], i),
    "perim":   lambda s, i: (-(s[0] + s[1]), -s[0] * s[1], i),
}


def _maxrects(sizes, bin_w, bin_h, score, order_key):
    """Place every (w, h) in `sizes` inside bin_w x bin_h. Returns positions in
    the order of `sizes`, or None if something did not fit."""
    free = [(0, 0, bin_w, bin_h)]
    placed = [None] * len(sizes)
    for i in sorted(range(len(sizes)), key=lambda i: order_key(sizes[i], i)):
        w, h = sizes[i]
        best = None
        for (fx, fy, fw, fh) in free:
            if fw < w or fh < h:
                continue
            key = score(w, h, fx, fy, fw, fh)
            if best is None or key < best[0]:
                best = (key, fx, fy)
        if best is None:
            return None
        _, x, y = best
        placed[i] = (x, y)
        free = _split_free(free, (x, y, w, h))
    return placed


def pack_rects(sizes, gutter, grid, size_align=4, max_width=4096):
    """Lay out `sizes` (a list of (w, h) in pixels) as tightly as this can
    manage. Returns (atlas_w, atlas_h, positions).

    `gutter` px is kept between every pair of parts and around the outside, so
    bilinear sampling at a block's edge cannot pull in its neighbour.

    `grid` is the alignment every POSITION must land on. The manifest stores
    atlas coordinates in pts, as round(px / density), so a part placed off the
    density grid would be recorded at a position it is not actually at, and
    every block in it would be sampled half a pixel out. Each part's footprint
    is rounded up to that grid and the origin sits on it, so every position
    derived from them does too. `size_align` is only cosmetic: it rounds the
    finished atlas dimensions, and does not have to divide `grid`.

    The width is not fixed. Every width from "just wide enough for the widest
    part" upwards is tried against every heuristic/order pair, each packed
    into an unbounded-height bin, and whichever combination yields the least
    area wins. Trying them all costs about a second and is worth it: on this
    kit the best pairing beats the worst by a factor of four, and which one
    wins changes as parts change size -- so picking one by hand today would
    quietly stop being the right choice later.
    """
    def up(v, a):
        return -(-v // a) * a

    # Each part reserves its own size plus one gutter; the matching gutter on
    # the left and top comes from the origin offset at the end.
    footprints = [(up(w + gutter, grid), up(h + gutter, grid)) for w, h in sizes]
    widest = max(w for w, _ in footprints)
    if widest + gutter > max_width:
        raise SystemExit(f"A part is {widest}px wide, wider than the {max_width}px atlas limit.")

    total = sum(w * h for w, h in footprints)
    # Past ~2.2x the square-root width the atlas is all but guaranteed to be
    # wider than it needs to be; below `widest` nothing fits at all.
    hi_w = min(max_width, max(widest, up(int(2.2 * math.sqrt(total)), grid)))

    best = None
    for hname, score in PACK_HEURISTICS.items():
        for oname, order_key in PACK_ORDERS.items():
            w = up(widest, grid)
            while w <= hi_w:
                placed = _maxrects(footprints, w, 1 << 24, score, order_key)
                if placed:
                    used_w = max(x + fw for (x, _), (fw, _f) in zip(placed, footprints))
                    used_h = max(y + fh for (_, y), (_f, fh) in zip(placed, footprints))
                    atlas_w = up(used_w + gutter, size_align)
                    atlas_h = up(used_h + gutter, size_align)
                    key = (atlas_w * atlas_h, max(atlas_w, atlas_h), atlas_w, hname, oname)
                    if best is None or key < best[0]:
                        best = (key, atlas_w, atlas_h,
                                [(x + gutter, y + gutter) for x, y in placed])
                w += grid

    if best is None:
        raise SystemExit("Could not pack the atlas -- no bin width fitted every part.")

    _, atlas_w, atlas_h, positions = best

    # The invariants the rest of the pipeline relies on. Cheap, and a silent
    # breach here would show up as blurred or shifted artwork, not a crash.
    for (x, y), (w, h) in zip(positions, sizes):
        assert x % grid == 0 and y % grid == 0, "part placed off the density grid"
        assert x + w <= atlas_w and y + h <= atlas_h, "part placed outside the atlas"
    for i in range(len(positions)):
        for j in range(i + 1, len(positions)):
            (ax, ay), (aw, ah) = positions[i], sizes[i]
            (bx, by), (bw, bh) = positions[j], sizes[j]
            assert (ax >= bx + bw + gutter or bx >= ax + aw + gutter or
                    ay >= by + bh + gutter or by >= ay + ah + gutter), \
                "parts overlap or are closer than the gutter"

    return atlas_w, atlas_h, positions


def pack_atlas(kit):
    kit_dir = KIT_ROOT / kit
    parts_dir = kit_dir / "parts"
    parts = []
    aliases = []
    for json_path in sorted(parts_dir.glob("*.json")):
        meta = json.loads(json_path.read_text())
        if meta.get("blocks_from"):
            aliases.append(meta)
            continue
        png_path = parts_dir / f"{meta['name']}.png"
        img = Image.open(png_path)
        parts.append((meta, img))

    if not parts:
        raise SystemExit("No parts/ found -- run `render` first.")

    # A part whose spec is gone still gets packed and still generates its
    # Skins:: entry, so deleting only the spec leaves a stale skin in the
    # header that refers to a member nobody declares any more. Hand-authored
    # parts with no spec are legitimate, so warn rather than fail.
    spec_names = {p.stem for p in (kit_dir / "specs").glob("*.yaml")}
    orphans = [m["name"] for m in [mm for mm, _ in parts] + aliases
               if m["name"] not in spec_names]
    if orphans:
        print(f"warning: parts with no spec in specs/: {', '.join(sorted(orphans))}\n"
              f"         they are still packed and still generate Skins:: entries -- "
              f"delete parts/<name>.png and .json if that is not what you want.",
              file=sys.stderr)

    density = parts[0][0]["density"]
    for meta, _ in parts:
        if meta["density"] != density:
            raise SystemExit(f"Density mismatch: {meta['name']} was rendered at {meta['density']}x, "
                              f"expected {density}x. Re-render everything at one consistent density.")

    # 1pt of clear space around every part, and positions on the density grid
    # so the pts coordinates in the manifest are exact rather than rounded.
    GUTTER = T.px(1, density)
    atlas_w, atlas_h, positions = pack_rects([img.size for _, img in parts],
                                             gutter=GUTTER, grid=density)

    used = sum(w * h for w, h in (img.size for _, img in parts))
    print(f"Atlas {atlas_w}x{atlas_h} = {atlas_w * atlas_h} px, "
          f"{used * 100 / (atlas_w * atlas_h):.1f}% occupied by artwork")

    atlas = Image.new("RGBA", (atlas_w, atlas_h), (0, 0, 0, 0))
    manifest = []
    for (meta, img), (x, y) in zip(parts, positions):
        atlas.alpha_composite(img, (x, y))
        manifest.append(dict(meta, atlas_x_pts=round(x / density), atlas_y_pts=round(y / density)))

    # Aliases take the source's block geometry (position, size, strip layout,
    # states) and keep their own blueprint fields. They are appended in name
    # order after the real parts, which keeps the generated header stable.
    by_name = {m["name"]: m for m in manifest}
    for alias in sorted(aliases, key=lambda m: m["name"]):
        src = by_name.get(alias["blocks_from"])
        if src is None:
            raise SystemExit(f"{alias['name']}: blocks_from names {alias['blocks_from']!r}, "
                             f"which has no part -- render it first.")
        entry = dict(alias)
        for k in ("atlas_x_pts", "atlas_y_pts", "size_pts", "axis",
                  "block_spacing_pts", "states"):
            entry[k] = src[k]
        # A frame the alias does not state is the source's: an alias usually
        # differs only in padding/spacing, and silently losing the frame would
        # smear its borders when stretched.
        if entry.get("frame_pts") is None:
            entry["frame_pts"] = src["frame_pts"]
        manifest.append(entry)

    return atlas, manifest, density


# Widgets whose skin pointer isn't Skins::<Name> -- everything else defaults to that.
CPP_TARGET_OVERRIDES = {
    "PlusMinusToggle": "_pPlusMinusToggleSkin",
    # The split handles are DoubleSkins: a grey bar with a transparent
    # dot overlay on top. Both layers are generated here as private
    # BlockSkins; header_shell.h combines each pair into Skins::SplitHandleX /
    # Skins::SplitHandleY just after the generated block.
    "SplitHandleX":     "_pSplitHandleXBarSkin",
    "SplitHandleXDots": "_pSplitHandleXDotsSkin",
    "SplitHandleY":     "_pSplitHandleYBarSkin",
    "SplitHandleYDots": "_pSplitHandleYDotsSkin",
}


def fmt_pts(v):
    """Format a pts value for C++. WonderGUI's `pts` is a float (see
    `typedef float pts` in wg_gfxtypes.h), so a half-point offset is legal and
    sometimes necessary -- an overlay whose glyph has to sit inside a rigid run
    may not land on the integer grid. int() here silently truncated such a
    value (2.5 -> 2), moving the run by half a point with nothing to show for
    it, so integral values print as integers and the rest keep their decimals.
    """
    f = float(v)
    return str(int(f)) if f == int(f) else repr(round(f, 4))


def fmt_border(v):
    if v is None:
        return None
    t, r, b, l = border_tuple(v)
    if t == r == b == l:
        return fmt_pts(t)
    return f"{{ {fmt_pts(t)},{fmt_pts(r)},{fmt_pts(b)},{fmt_pts(l)} }}"


AXIS_CPP = {"x": "Axis::X", "y": "Axis::Y"}


def gen_skin_block(entry):
    target = CPP_TARGET_OVERRIDES.get(entry["name"], f"Skins::{entry['name']}")
    x, y = entry["atlas_x_pts"], entry["atlas_y_pts"]
    w, h = entry["size_pts"]
    lines = [f"\t\t{target} = BlockSkin::create(WGBP(BlockSkin,",
             f"\t\t\t_.surface = pSkinBlocks,",
             f"\t\t\t_.firstBlock = {{ {fmt_pts(x)},{fmt_pts(y)},{fmt_pts(w)},{fmt_pts(h)} }},"]

    if entry["axis"] in ("x", "y"):
        lines.append(f"\t\t\t_.axis = {AXIS_CPP[entry['axis']]},")
        lines.append(f"\t\t\t_.blockSpacing = {fmt_pts(entry['block_spacing_pts'])},")

    frame = fmt_border(entry["frame_pts"])
    if frame is not None:
        lines.append(f"\t\t\t_.frame = {frame},")
    padding = fmt_border(entry["padding_pts"])
    if padding is not None:
        lines.append(f"\t\t\t_.padding = {padding},")
    # Skin::spacing is an outer margin (Skin::margin() returns it): it shrinks
    # the rect the skin draws into and grows the widget's default size, so a
    # widget carries its own separation from its neighbours instead of every
    # caller remembering to set panel spacing. Each side gets the full value,
    # so two adjacent widgets end up 2 x spacing apart.
    spacing = fmt_border(entry.get("spacing_pts"))
    if spacing is not None:
        lines.append(f"\t\t\t_.spacing = {spacing},")

    for rp in rigid_parts(entry):
        field = "rigidPartX" if rp["axis"] == "x" else "rigidPartY"
        enum = "YSections" if rp["axis"] == "x" else "XSections"
        # `sections` may name several, e.g. "Top|Bottom". Qualify each one:
        # "YSections::Top|Bottom" is not valid C++, and both enums define
        # operator| (plus an All) in wg_gfxtypes.h.
        sections = " | ".join(f"{enum}::{s.strip()}" for s in str(rp["sections"]).split("|"))
        lines.append(f"\t\t\t_.{field} = {{{fmt_pts(rp['begin_pts'])},{fmt_pts(rp['length_pts'])},{sections}}},")

    # content_shift moves the widget's CONTENT (label, icon) for a state,
    # without touching the artwork: the classic push-button effect where the
    # caption sinks down-right with the surface. BlockSkin adds it to
    # _contentOfs (wg_stateskin.cpp), in pts, so it costs no atlas space.
    #
    # It must not disturb the block order. wg_blockskin.cpp assigns block
    # positions as `blockOfs + pitch * index` where index counts only the
    # non-blockless entries, and the shift is tracked by a separate counter --
    # so annotating a state that already has a block is safe, and a state
    # WITHOUT one would need `blockless = true` as a third argument or it would
    # silently steal the next block in the strip. Only states listed in the
    # spec's `states` are annotated here, so that case cannot arise.
    shifts = entry.get("content_shift") or {}
    unknown = [k for k in shifts if k not in entry["states"]]
    if unknown:
        raise SystemExit(
            f"{entry['name']}: content_shift names {', '.join(unknown)}, which "
            f"{'is' if len(unknown) == 1 else 'are'} not in states: "
            f"{entry['states']}. A state with no block of its own needs a "
            f"blockless StateBP, which this generator does not emit.")

    def state_cpp(st):
        if st not in shifts:
            return f"State::{st}"
        x, y = shifts[st]
        return f"{{State::{st}, Coord({fmt_pts(x)},{fmt_pts(y)})}}"

    states = entry["states"]
    if not (len(states) == 1 and states[0] == "Default"):
        states_cpp = ", ".join(state_cpp(s) for s in states)
        lines.append(f"\t\t\t_.states = {{ {states_cpp} }}")
    else:
        lines[-1] = lines[-1].rstrip(",")  # drop trailing comma on last real field

    # Clean up: ensure no trailing comma before closing paren
    if lines[-1].endswith(","):
        lines[-1] = lines[-1][:-1]

    lines.append("\t\t));")
    return "\n".join(lines)


BEGIN_MARKER = "// >>> BEGIN GENERATED SKINS <<<"
END_MARKER = "// >>> END GENERATED SKINS <<<"

COLORS_BEGIN = "// >>> BEGIN GENERATED COLORS <<<"
COLORS_END = "// >>> END GENERATED COLORS <<<"


def _marker_line_matches(marker, shell):
    """Find occurrences of `marker` appearing as its OWN line (only leading/
    trailing whitespace beside it). A plain substring search is not safe here:
    if any hand-written prose elsewhere in header_shell.h happens to mention
    the marker text (e.g. explaining what the markers do), a naive
    str.split() would silently splice at the wrong spot instead of the real
    marker, quietly discarding everything in between. Returns a list of
    re.Match objects, in order."""
    pattern = re.compile(r"^[ \t]*" + re.escape(marker) + r"[ \t]*$", re.MULTILINE)
    return list(pattern.finditer(shell))


def gen_colors(kit, palette, density):
    """Emit the Colors:: constants declared under `exported_colors` in
    palette.yaml.

    These were hand-written C++ while the gradients lived in YAML, with
    nothing tying the two together -- so every palette change silently
    invalidated them, and Colors::Plate drifted to the gradient's TOP colour
    while the bitmap's middle was 14 levels darker. Anything using it to sit
    flush against a Plate was visibly off.

    `center_of` is the important form: it MEASURES the centre pixel of a
    rendered part, so the constant is whatever the bitmap actually is, however
    the recipe draws it. The others are conveniences for colours a bitmap
    doesn't define.
    """
    parts_dir = KIT_ROOT / kit / "parts"
    lines = []
    for name, src in (palette.get("exported_colors") or {}).items():
        if "center_of" in src:
            part = src["center_of"]
            meta = json.loads((parts_dir / f"{part}.json").read_text())
            img = Image.open(parts_dir / f"{part}.png").convert("RGBA")
            d = meta.get("density", density)
            w, h = (round(v * d) for v in meta["size_pts"])
            rgb = img.crop((0, 0, w, h)).getpixel((w // 2, h // 2))[:3]
            auto = f"measured: centre pixel of parts/{part}.png"
        elif "border_of" in src:
            rgb = tuple(palette[src["border_of"]]["border"][:3])
            auto = f"palette: {src['border_of']}.border"
        elif "top_of" in src or "bottom_of" in src:
            key = "top_of" if "top_of" in src else "bottom_of"
            rgb = tuple(palette[src[key]][key[:-3]][:3])
            auto = f"palette: {src[key]}.{key[:-3]}"
        elif "rgb" in src:
            rgb = tuple(src["rgb"])
            auto = ""
        else:
            raise SystemExit(f"exported_colors[{name}]: need one of "
                             f"center_of / border_of / top_of / bottom_of / rgb")
        note = src.get("note", auto)
        if src.get("comment"):
            if lines:
                lines.append("")
            for cl in src["comment"].rstrip("\n").split("\n"):
                lines.append(f"\t\t// {cl}".rstrip())
        decl = f"\t\tinline const Color\t{name} = Color({rgb[0]},{rgb[1]},{rgb[2]});"
        lines.append(f"{decl}\t\t// {note}" if note else decl)
    return "\n".join(lines)


def _splice(shell, begin, end, body):
    """Replace the region between the `begin` and `end` marker lines with
    `body`, keeping the marker lines themselves."""
    begin_matches = _marker_line_matches(begin, shell)
    end_matches = _marker_line_matches(end, shell)

    if len(begin_matches) != 1 or len(end_matches) != 1:
        raise SystemExit(
            f"header_shell.h must contain exactly one {begin!r} line "
            f"and one {end!r} line (found {len(begin_matches)} / "
            f"{len(end_matches)}). If these strings appear elsewhere too "
            f"(e.g. in an explanatory comment), reword that mention so it "
            f"isn't a standalone line matching the marker exactly."
        )
    if begin_matches[0].start() >= end_matches[0].start():
        raise SystemExit(f"header_shell.h: {begin!r} must come before {end!r}")

    # post starts at the END marker's own line start (the match includes that
    # line's leading whitespace), so its original indentation is preserved and
    # nothing is added in front of it.
    pre = shell[: begin_matches[0].end()]
    post = shell[end_matches[0].start() :]
    return f"{pre}\n{body}\n{post}"


def generate_header(kit, manifest, palette, density):
    kit_dir = KIT_ROOT / kit
    shell = (kit_dir / "header_shell.h").read_text()

    shell = _splice(shell, COLORS_BEGIN, COLORS_END, gen_colors(kit, palette, density))
    shell = _splice(shell, BEGIN_MARKER, END_MARKER,
                    "\n\n".join(gen_skin_block(e) for e in manifest))
    return shell


# ---------------------------------------------------------------------------
# Faithful port of GfxDeviceGen1::blitNinePatch, used to render the preview's
# stretch demos. CSS border-image cannot express rigidPartX/Y at all, so
# simulating the real algorithm here is the only way the preview can show what
# the widget will actually look like when stretched.
# ---------------------------------------------------------------------------
def rigid_parts(entry):
    """A spec's rigid parts as a list. `rigid_part` may be a single mapping or
    a list of them -- a block can pin BOTH axes at once (BlockSkin has separate
    rigidPartX and rigidPartY fields, and blitNinePatch nests them: it splits
    the centre cell by rigidPartY, then applies rigidPartX within each of the
    resulting bands). A bar that is stretched along its length but may also be
    drawn at a different thickness needs both, or the glyph smears on the axis
    that was left unpinned."""
    rp = entry.get("rigid_part")
    if not rp:
        return []
    return list(rp) if isinstance(rp, list) else [rp]


def rebase_rigid(rp, frame_px, block_size, density):
    """Convert a spec rigid_part into middle-band-relative pixels.

    BlockSkin stores `begin` in BLOCK coordinates then rebases it onto the
    stretchable middle band (`ofs -= frame.top`, clamped to the band), so we
    do exactly the same to stay in step with it.
    """
    t, r, b, l = frame_px
    sw, sh = block_size
    ofs = round(rp["begin_pts"] * density)
    length = round(rp["length_pts"] * density)
    if rp["axis"] == "y":
        mid, ofs = sh - t - b, ofs - t
    else:
        mid, ofs = sw - l - r, ofs - l
    if ofs < 0:
        length, ofs = length + ofs, 0
    if ofs + length > mid:
        length = mid - ofs
    # rigidPartX is masked by YSections (rows), rigidPartY by XSections (cols).
    names = {s.strip() for s in str(rp["sections"]).split("|")}
    if "All" in names:
        names = {"Top", "Center", "Bottom"} if rp["axis"] == "x" else {"Left", "Center", "Right"}
    return dict(axis=rp["axis"], ofs=ofs, len=max(length, 0), sections=names)


def rigid_spans(src_len, dst_len, ofs, length):
    """Split one stretchable band into (src_ofs, src_len, dst_len) runs.

    Mirrors the arithmetic in blitNinePatch: the rigid run keeps its natural
    length and whatever destination space is left over is divided between the
    two flanks in proportion to their SOURCE lengths. Note the guard -- the
    engine divides by (lead+trail), so a rigid run covering the whole band
    would divide by zero there; we degrade to a plain stretch instead.
    """
    lead_src, trail_src = ofs, src_len - ofs - length
    total_src = lead_src + trail_src
    if total_src <= 0 or length <= 0:
        return [(0, src_len, dst_len)]
    mid_dst = min(length, dst_len)
    lead_dst = (dst_len - mid_dst) * lead_src // total_src
    trail_dst = dst_len - mid_dst - lead_dst
    return [(0, lead_src, lead_dst),
            (lead_src, length, mid_dst),
            (lead_src + length, trail_src, trail_dst)]


def simulate_stretch(block, frame_px, target_px, rigids=()):
    """Stretch a single state block to `target_px` the way WonderGUI would.

    Source and destination share a px-per-pt density here, so the frame keeps
    its pixel size and only the middle bands scale.
    """
    t, r, b, l = frame_px
    sw, sh = block.size
    tw, th = target_px
    out = Image.new("RGBA", (tw, th), (0, 0, 0, 0))

    cols = [(0, l, 0, l, "Left"),
            (l, sw - l - r, l, tw - l - r, "Center"),
            (sw - r, r, tw - r, r, "Right")]
    rows = [(0, t, 0, t, "Top"),
            (t, sh - t - b, t, th - t - b, "Center"),
            (sh - b, b, th - b, b, "Bottom")]

    rx = next((r for r in rigids if r["axis"] == "x"), None)
    ry = next((r for r in rigids if r["axis"] == "y"), None)

    for sx, swid, dx, dwid, cname in cols:
        if swid <= 0 or dwid <= 0:
            continue
        for sy, shgt, dy, dhgt, rname in rows:
            if shgt <= 0 or dhgt <= 0:
                continue
            # rigidPartY subdivides the vertical middle of the named X sections
            vspans = (rigid_spans(shgt, dhgt, ry["ofs"], ry["len"])
                      if ry and rname == "Center" and cname in ry["sections"]
                      else [(0, shgt, dhgt)])
            # rigidPartX subdivides the horizontal middle of the named Y sections
            hspans = (rigid_spans(swid, dwid, rx["ofs"], rx["len"])
                      if rx and cname == "Center" and rname in rx["sections"]
                      else [(0, swid, dwid)])
            dyy = dy
            for vso, vsl, vdl in vspans:
                dxx = dx
                for hso, hsl, hdl in hspans:
                    if hsl > 0 and vsl > 0 and hdl > 0 and vdl > 0:
                        piece = block.crop((sx + hso, sy + vso,
                                            sx + hso + hsl, sy + vso + vsl))
                        if (hdl, vdl) != (hsl, vsl):
                            piece = piece.resize((hdl, vdl), Image.BILINEAR)
                        out.paste(piece, (dxx, dyy))
                    dxx += hdl
                dyy += vdl
    return out


# ---------------------------------------------------------------------------
# preview.html: contact sheet + simulated stretch check
# ---------------------------------------------------------------------------
def build_preview_html(kit, atlas, manifest, density):
    import base64
    import io

    by_name = {m["name"]: m for m in manifest}

    def block_of(meta, state_index=0):
        """The `state_index`-th state block of a part, cropped from the atlas."""
        w, h = (round(v * density) for v in meta["size_pts"])
        x = round(meta["atlas_x_pts"] * density)
        y = round(meta["atlas_y_pts"] * density)
        sp = round(meta["block_spacing_pts"] * density)
        if meta["axis"] == "x":
            x += state_index * (w + sp)
        elif meta["axis"] == "y":
            y += state_index * (h + sp)
        return atlas.crop((x, y, x + w, y + h))

    def stretched(meta, target_px, state_index=0):
        frame_px = tuple(round(v * density) for v in border_tuple(meta["frame_pts"] or 0))
        block = block_of(meta, state_index)
        rigids = [rebase_rigid(rp, frame_px, block.size, density)
                  for rp in rigid_parts(meta)]
        return simulate_stretch(block, frame_px, target_px, rigids)

    def compose(meta, target_px, state_index=0):
        """An overlay part rendered the way the widget will actually look: its
        `preview_over` part underneath, both nine-patched to the same size.
        Without this a DoubleSkin's front layer shows up in the preview as a
        few dots on a checkerboard, which says nothing about whether the
        finished widget is right."""
        img = stretched(meta, target_px, state_index)
        back_name = meta.get("preview_over")
        if not back_name or back_name not in by_name:
            return img
        back_meta = by_name[back_name]
        # States are matched by NAME, not index: the overlay carries fewer
        # states than the bar (Default/Disabled vs four), so index 1 means
        # Hovered on one and Disabled on the other.
        want = meta["states"][state_index]
        bi = back_meta["states"].index(want) if want in back_meta["states"] else 0
        out = stretched(back_meta, target_px, bi)
        out.alpha_composite(img)
        return out

    def b64_crop(meta):
        x, y = round(meta["atlas_x_pts"] * density), round(meta["atlas_y_pts"] * density)
        w, h = round(meta["size_pts"][0] * density), round(meta["size_pts"][1] * density)
        n = len(meta["states"])
        if meta["axis"] == "x":
            full = atlas.crop((x, y, x + n * w + (n - 1) * round(meta["block_spacing_pts"] * density), y + h))
        elif meta["axis"] == "y":
            full = atlas.crop((x, y, x + w, y + n * h + (n - 1) * round(meta["block_spacing_pts"] * density)))
        else:
            full = atlas.crop((x, y, x + w, y + h))
        buf = io.BytesIO()
        full.save(buf, "PNG")
        return base64.b64encode(buf.getvalue()).decode()

    css = """
    body{font-family:sans-serif;background:#eef0f3;padding:20px;color:#222}
    h2{font-size:13px;margin:22px 0 6px}
    .meta{font-size:11px;color:#667;margin-bottom:6px}
    .ok{color:#186a3b}
    .row{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin-bottom:8px}
    .chip{image-rendering:pixelated;border:1px solid #ccc;background:
      repeating-conic-gradient(#ddd 0% 25%, #fff 0% 50%) 50% / 12px 12px}
    .demo{position:relative}
    .demo img{display:block;width:100%;height:100%;image-rendering:pixelated}
    .content{position:absolute;display:flex;align-items:center;justify-content:flex-start;
      outline:1px dashed rgba(0,0,0,.35);color:#08306b;font-weight:600;font-size:12px}
    """
    html = [f'<!doctype html><html><head><meta charset="utf-8"><title>{kit} preview</title><style>{css}</style></head><body>']
    html.append(f"<h1>{kit} widgetkit preview</h1>")

    zoom = 4          # CSS px per pt in this preview

    for meta in manifest:
        b64 = b64_crop(meta)
        name = meta["name"]
        html.append(f"<h2>{name}</h2>")
        rigid_note = ""
        for rp in rigid_parts(meta):
            rigid_note += (f" &middot; <span class='ok'>rigidPart{rp['axis'].upper()} "
                           f"{rp['begin_pts']}..{rp['begin_pts'] + rp['length_pts']}pts "
                           f"({rp['sections']}) held rigid below</span>")
        # Spacing is an outer margin, so it is not in the bitmap and cannot be
        # drawn here -- but it changes how the widget sits next to its
        # neighbours, so at least say it out loud.
        spacing_note = (f" &middot; <span class='ok'>spacing_pts: {meta['spacing_pts']} "
                        f"(outer margin, not in the bitmap)</span>"
                        if meta.get("spacing_pts") else "")
        shift_note = "".join(
            f" &middot; <span class='ok'>{st} shifts content {sh[0]},{sh[1]}pts</span>"
            for st, sh in (meta.get("content_shift") or {}).items())
        spacing_note += shift_note
        html.append(f"<div class='meta'>states: {', '.join(meta['states'])} &middot; "
                     f"size_pts: {meta['size_pts']} &middot; frame_pts: {meta['frame_pts']} &middot; "
                     f"padding_pts: {meta['padding_pts']}{spacing_note}{rigid_note}</div>")
        html.append("<div class='row'>")
        html.append(f"<img class='chip' style='width:auto;height:{meta['size_pts'][1]*zoom if meta['axis']!='y' else meta['size_pts'][1]*len(meta['states'])*zoom}px' "
                     f"src='data:image/png;base64,{b64}'>")

        # Any framed block gets stretch demos, including single-state panels
        # (axis "single"). Those were excluded before, which is precisely why
        # Plate/Canvas/Window went so long with no frame at all: the preview
        # never showed them stretched, so the smeared borders never appeared.
        if meta["frame_pts"] is not None:
            t, r, b, l = border_tuple(meta["frame_pts"])
            w_pts, h_pts = meta["size_pts"]
            frame_px = tuple(round(v * density) for v in (t, r, b, l))

            # Only demo an axis that has stretchable material left over. A
            # horizontal scrollbar handle's frame spans its full height by
            # design (top 8 + bottom 8 of a 16pt block), so a "taller" demo
            # would show a legitimately empty band and read as a defect.
            stretch_x, stretch_y = (l + r) < w_pts, (t + b) < h_pts
            if stretch_x and stretch_y:
                # First demo shows the widget stretched along the axis it is
                # actually used on, so it reads as normal usage; the second
                # stretches both, to stress the other axis and any rigid part
                # pinned on it. A split bar grows along its length only, so
                # showing it 2x WIDE first was misleading.
                primary = meta.get("stretch_axis") or "x"
                if primary == "y":
                    sizes = [(w_pts, h_pts * 2), (w_pts * 2, h_pts * 3)]
                else:
                    sizes = [(w_pts * 2, h_pts), (w_pts * 3, h_pts * 2)]
            elif stretch_x:
                sizes = [(w_pts * 2, h_pts), (w_pts * 4, h_pts)]
            elif stretch_y:
                sizes = [(w_pts, h_pts * 2), (w_pts, h_pts * 4)]
            else:
                sizes = []

            pt, pr, pb, pl = border_tuple(meta["padding_pts"]) or (0, 0, 0, 0)
            for w, h in sizes:
                img = compose(meta, (round(w * density), round(h * density)))
                buf = io.BytesIO()
                img.save(buf, "PNG")
                d64 = base64.b64encode(buf.getvalue()).decode()
                # The dashed box is the content rect (size minus padding) --
                # it shows at a glance whether text would collide with an
                # inset glyph such as the select box's arrow.
                html.append(
                    f"<div class='demo' style='width:{w*zoom}px;height:{h*zoom}px' "
                    f"title='{name} stretched to {w}x{h} pts'>"
                    f"<img src='data:image/png;base64,{d64}'>"
                    f"<div class='content' style='top:{pt*zoom}px;right:{pr*zoom}px;"
                    f"bottom:{pb*zoom}px;left:{pl*zoom}px'>Aa</div></div>")
        html.append("</div>")

    html.append("</body></html>")
    return "\n".join(html)


# ---------------------------------------------------------------------------
def cmd_pack(kit):
    atlas, manifest, density = pack_atlas(kit)
    kit_dir = KIT_ROOT / kit

    atlas_name = f"{kit}_skinblocks.png"
    header_name = f"wg_{kit}.h"

    atlas.save(kit_dir / atlas_name)
    palette = yaml.safe_load((kit_dir / "palette.yaml").read_text())
    (kit_dir / header_name).write_text(generate_header(kit, manifest, palette, density))
    (kit_dir / "preview.html").write_text(build_preview_html(kit, atlas, manifest, density))

    (REPO_ROOT / "resources").mkdir(parents=True, exist_ok=True)
    (REPO_ROOT / "src" / "widgetkits").mkdir(parents=True, exist_ok=True)
    atlas.save(REPO_ROOT / "resources" / atlas_name)
    (REPO_ROOT / "src" / "widgetkits" / header_name).write_text((kit_dir / header_name).read_text())

    print(f"Packed {len(manifest)} widgets into {atlas.size[0]}x{atlas.size[1]} atlas @ {density}x density")
    print(f"Wrote {kit_dir / atlas_name}, {kit_dir / header_name}, {kit_dir / 'preview.html'}")
    print(f"Deployed to resources/{atlas_name} and src/widgetkits/{header_name}")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    r = sub.add_parser("render")
    r.add_argument("kit")
    r.add_argument("names", nargs="*")
    r.add_argument("--force", action="store_true")
    r.add_argument("--density", type=float, default=DEFAULT_DENSITY)

    p = sub.add_parser("pack")
    p.add_argument("kit")

    args = ap.parse_args()
    if args.cmd == "render":
        cmd_render(args.kit, args.names, args.force, args.density)
    elif args.cmd == "pack":
        cmd_pack(args.kit)


if __name__ == "__main__":
    main()
