#!/usr/bin/ruby
#
# Convert images to WonderGUI surfaces (.surf) and embed them in a C++ source
# file, so they can be loaded with SurfaceReader::readSurfaceFromMemory()
# without an image decoder or access to the file system.
#
# Usage:
#
#   embed_images.rb --image2surf=<path> --output=<file.cpp> --namespace=<ns>
#                   [--pixelcomp=<compression>] <name>=<image> [<name>=<image> ...]
#
# For each <name>=<image> the output defines
#
#   extern const char <name>[];		// The .surf data.
#   extern const int  <name>Size;		// Size of the .surf data in bytes.
#
# in namespace <ns>. Pixel compression defaults to LZWG.
#
# <path> is the image2surf tool, built from src/tools/image2surf.

require 'tmpdir'
require 'fileutils'

image2surf = nil
output = nil
namespace = nil
pixelcomp = "LZWG"
entries = []

ARGV.each do |arg|
  case arg
  when /\A--image2surf=(.+)\z/ then image2surf = $1
  when /\A--output=(.+)\z/     then output = $1
  when /\A--namespace=(.+)\z/  then namespace = $1
  when /\A--pixelcomp=(.+)\z/  then pixelcomp = $1
  when /\A([A-Za-z_][A-Za-z0-9_]*)=(.+)\z/ then entries << [$1, $2]
  else
    abort "ERROR: Don't know what to do with argument '#{arg}'."
  end
end

abort "ERROR: --image2surf, --output and --namespace are mandatory." if !image2surf || !output || !namespace
abort "ERROR: No images given." if entries.empty?

src = "// Generated by scripts/embed_images.rb. Do not edit, regenerate instead.\n"
src << "//\n"
entries.each { |name, image| src << "//   #{name} <- #{File.basename(image)}\n" }
src << "\nnamespace #{namespace}\n{\n"

Dir.mktmpdir do |dir|
  entries.each do |name, image|
    surf = File.join(dir, name + ".surf")
    system(image2surf, "--pixelcomp=#{pixelcomp}", image, surf) or abort "ERROR: image2surf failed on '#{image}'."
    abort "ERROR: image2surf produced no output for '#{image}'." unless File.exist?(surf)

    bytes = File.binread(surf).bytes

    src << "\textern const int #{name}Size = #{bytes.length};\n"
    src << "\talignas(8) extern const char #{name}[#{bytes.length}] = {\n"
    bytes.each_slice(16) do |row|
      src << "\t\t" << row.map { |b| format("'\\x%02x'", b) }.join(",") << ",\n"
    end
    src << "\t};\n\n"
  end
end

src << "}\n"

File.write(output, src)
puts "Wrote #{output}"
