/*=========================================================================

                         >>> WonderGUI <<<

  This file is part of Tord Jansson's WonderGUI Graphics Toolkit
  and copyright (c) Tord Jansson, Sweden [tord.jansson@gmail.com].

                            -----------

  The WonderGUI Graphics Toolkit is free software; you can redistribute
  this file and/or modify it under the terms of the GNU General Public
  License as published by the Free Software Foundation; either
  version 2 of the License, or (at your option) any later version.

                            -----------

  The WonderGUI Graphics Toolkit is also available for use in commercial
  closed-source projects under a separate license. Interested parties
  should contact Tord Jansson [tord.jansson@gmail.com] for details.

=========================================================================*/
#include <wg_dx12backend.h>

namespace wg {

const char DX12Backend::g_fillVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;     // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;       // Offset into the color buffer.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_fillPS[] =

"struct PS_INPUT //from the VS_OUTPUT\n"
"{\n"
"	\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"	\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"\n"
"   \n"
"    return input.color;\n"
"\n"
"}\n"
;

const char DX12Backend::g_fillAAVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"    float2 textureSize;     // Not used here.\n"
"    uint flags;             // Not used here.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;     // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;       // Offset into the color buffer.\n"
"    uint extrasOfs : EXTRASOFS;     // Offset into the extras buffer.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float4 rect : TEXCOORD0;        // Center of the rectangle in xy, its radius in zw.\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    // The rectangle we are covering, as a center and a radius. Half a pixel is\n"
"    // added to the radius so that a pixel exactly on the edge comes out at full\n"
"    // coverage rather than half.\n"
"\n"
"    output.rect = extras[input.extrasOfs];\n"
"    output.rect.zw += float2(0.5f, 0.5f);\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_fillAAPS[] =

"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float4 rect : TEXCOORD0;        // Center of the rectangle in xy, its radius in zw.\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    // How far this pixel's center is from the center of the rectangle, against\n"
"    // how far it may be before it stops being covered. Anything in between is a\n"
"    // pixel the edge runs through, and gets partial coverage.\n"
"\n"
"    float4 color = input.color;\n"
"\n"
"    float2 middleOfs = abs(input.position.xy - input.rect.xy);\n"
"    float2 alphas = clamp(input.rect.zw - middleOfs, 0.0f, 1.0f);\n"
"\n"
"    color.a = input.color.a * alphas.x * alphas.y;\n"
"\n"
"    return color;\n"
"}\n"
;

const char DX12Backend::g_blitVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"    float2 textureSize;     // Size of blit source, in pixels.\n"
"    uint flags;             // Bit 0: source is alpha only.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;     // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;       // Offset into the color buffer.\n"
"    uint extrasOfs : EXTRASOFS;     // Offset into the extras buffer.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    // First extras entry holds source and destination origin, second one the\n"
"    // transform. Source coordinate is the destination offset run through the\n"
"    // transform, which is how flipping and rotation are handled.\n"
"\n"
"    float4 srcDst = extras[input.extrasOfs];\n"
"    float4 transform = extras[input.extrasOfs + 1];\n"
"\n"
"    float2 src = srcDst.xy;\n"
"    float2 dst = srcDst.zw;\n"
"\n"
"    float2 ofs = input.position - dst;\n"
"\n"
"    output.texUV = float2((src.x + ofs.x * transform.x + ofs.y * transform.z) / textureSize.x,\n"
"                          (src.y + ofs.x * transform.y + ofs.y * transform.w) / textureSize.y);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_blitPS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;\n"
"    float2 textureSize;\n"
"    uint flags;             // Bit 0: source is alpha only.\n"
"};\n"
"\n"
"Texture2D blitSource : register(t2);\n"
"SamplerState blitSampler : register(s0);\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    float4 texel = blitSource.Sample(blitSampler, input.texUV);\n"
"\n"
"    // An alpha only source has no color of its own, it just modulates the tint.\n"
"\n"
"    if ((flags & 1) != 0)\n"
"    {\n"
"        float4 color = input.color;\n"
"        color.a *= texel.a;\n"
"        return color;\n"
"    }\n"
"\n"
"    return texel * input.color;\n"
"}\n"
;

const char DX12Backend::g_blurPS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // Not used here.\n"
"    float2 textureSize;     // Not used here, the vertex shader has already used it.\n"
"    uint flags;             // Not used here.\n"
"    uint blurOfs;           // Where our 9 color matrices and 9 offsets start in extras.\n"
"};\n"
"\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"Texture2D blitSource : register(t2);\n"
"SamplerState blitSampler : register(s0);\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    // An alpha only source has no color to blur, so its alpha is blurred instead\n"
"    // and the tint supplies the color. The red row of the matrix is used as the\n"
"    // weight, the three rows being the same for an ordinary brush.\n"
"\n"
"    if ((flags & 1u) != 0u)\n"
"    {\n"
"        float alpha = 0.0f;\n"
"\n"
"        [unroll]\n"
"        for (uint j = 0u; j < 9u; j++)\n"
"        {\n"
"            float2 ofs = extras[blurOfs + 9u + j].xy;\n"
"\n"
"            alpha += blitSource.Sample(blitSampler, input.texUV + ofs).a * extras[blurOfs + j].x;\n"
"        }\n"
"\n"
"        float4 alphaColor = input.color;\n"
"        alphaColor.a *= alpha;\n"
"\n"
"        return alphaColor;\n"
"    }\n"
"\n"
"    // Nine taps around this one, each weighted per channel by its own row of the\n"
"    // brush's color matrix. The offsets are in texture coordinates, worked out\n"
"    // from the blur radius and the size of the source.\n"
"\n"
"    float4 color = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    [unroll]\n"
"    for (uint i = 0u; i < 9u; i++)\n"
"    {\n"
"        float2 ofs = extras[blurOfs + 9u + i].xy;\n"
"\n"
"        color += blitSource.Sample(blitSampler, input.texUV + ofs) * extras[blurOfs + i];\n"
"    }\n"
"\n"
"    // A blur has no alpha of its own. What comes out is opaque, and the tint is\n"
"    // what decides how much of it reaches the canvas.\n"
"\n"
"    color.a = 1.0f;\n"
"\n"
"    return color * input.color;\n"
"}\n"
;

const char DX12Backend::g_lineVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"    float2 textureSize;     // Not used here.\n"
"    uint flags;             // Not used here.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;     // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;       // Offset into the color buffer.\n"
"    uint extrasOfs : EXTRASOFS;     // Offset into the extras buffer.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float4 lineInfo : TEXCOORD0;    // Offset, half width, slope, and whether it is steep.\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    // The line itself, which every vertex of the quad carries unchanged. The\n"
"    // pixel shader works out how much of each pixel the line covers.\n"
"\n"
"    output.lineInfo = extras[input.extrasOfs];\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_linePS[] =

"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float4 lineInfo : TEXCOORD0;    // Offset, half width, slope, and whether it is steep.\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    float s = input.lineInfo.x;\n"
"    float w = input.lineInfo.y;\n"
"    float slope = input.lineInfo.z;\n"
"\n"
"    // A steep line runs mainly vertically, so x and y swap roles. Carrying it as\n"
"    // a number rather than a branch keeps the maths to one expression.\n"
"\n"
"    float ifSteep = input.lineInfo.w;\n"
"    float ifMild = 1.0f - ifSteep;\n"
"\n"
"    float2 pos = input.position.xy;\n"
"\n"
"    float along = pos.x * ifMild + pos.y * ifSteep;\n"
"    float across = pos.x * ifSteep + pos.y * ifMild;\n"
"\n"
"    // Distance from the center of the line, against its half width. A pixel\n"
"    // further away than that is outside the line, one closer is fully inside.\n"
"\n"
"    float4 color = input.color;\n"
"\n"
"    color.a = input.color.a * clamp(w - abs(across - s - along * slope), 0.0f, 1.0f);\n"
"\n"
"    return color;\n"
"}\n"
;

const char DX12Backend::g_segmentsVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"    float2 textureSize;     // Not used here.\n"
"    uint flags;             // Not used here.\n"
"    uint blurOfs;           // Not used here.\n"
"    uint edgemapEdges;      // Not used here.\n"
"    uint edgemapPitch;      // Not used here.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;         // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;           // Offset into the color buffer.\n"
"    uint extrasOfs : EXTRASOFS;         // Offset into the extras buffer.\n"
"    float2 texUV : TEXCOORD0;           // Column in x, distance down the column in y.\n"
"    float2 colorstripUV : COLORSTRIP;   // Where in the edgemap this corner's colors start.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"    float2 colorstripUV : TEXCOORD1;\n"
"    nointerpolation float2 colorstripPitch : TEXCOORD2;\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    output.texUV = input.texUV;\n"
"    output.colorstripUV = input.colorstripUV;\n"
"\n"
"    // How far to step through the palette for each segment. Zero on an axis with\n"
"    // no colorstrip, which then keeps reading the same color.\n"
"\n"
"    output.colorstripPitch = extras[input.extrasOfs].xy;\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_segmentsPS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // Not used here.\n"
"    float2 textureSize;     // Not used here.\n"
"    uint flags;             // Not used here.\n"
"    uint blurOfs;           // Not used here.\n"
"    uint edgemapEdges;      // Edges to walk, one fewer than the segments we render.\n"
"    uint edgemapPitch;      // Edges per column in the edgemap's buffer.\n"
"};\n"
"\n"
"StructuredBuffer<float4> edgemap : register(t3);\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"    float2 colorstripUV : TEXCOORD1;\n"
"    nointerpolation float2 colorstripPitch : TEXCOORD2;\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    // Walking down a column of the edgemap, one edge at a time. Each edge says\n"
"    // where it begins and how steeply it runs, which is enough to tell how much\n"
"    // of this pixel falls above it. The difference between one edge's coverage\n"
"    // and the next is how much of the pixel belongs to the segment between them.\n"
"\n"
"    int nEdges = int(edgemapEdges);\n"
"    int pitch = int(edgemapPitch);\n"
"\n"
"    int column = int(input.texUV.x) * pitch;\n"
"\n"
"    int2 colorOfs = (int2) input.colorstripUV;\n"
"    int2 colorstripPitch = (int2) input.colorstripPitch;\n"
"\n"
"    float totalAlpha = 0.0f;\n"
"    float3 rgbAcc = float3(0.0f, 0.0f, 0.0f);\n"
"\n"
"    float factor = 1.0f;\n"
"\n"
"    for (int i = 0; i < nEdges; i++)\n"
"    {\n"
"        // A segment's color is its horizontal colorstrip times its vertical one.\n"
"        // One of the two is white when only the other has a strip.\n"
"\n"
"        float4 col = edgemap[colorOfs.x] * edgemap[colorOfs.y];\n"
"\n"
"        colorOfs += colorstripPitch;\n"
"\n"
"        float4 edge = edgemap[column + i];\n"
"\n"
"        float x = (input.texUV.y - edge.r) * edge.g;\n"
"\n"
"        float adder = edge.g / 2.0f;\n"
"\n"
"        if (x < 0.0f)\n"
"            adder = edge.b;\n"
"        else if (x + edge.g > 1.0f)\n"
"            adder = edge.a;\n"
"\n"
"        float factor2 = clamp(x + adder, 0.0f, 1.0f);\n"
"\n"
"        float useFactor = (factor - factor2) * col.a;\n"
"\n"
"        totalAlpha += useFactor;\n"
"        rgbAcc += col.rgb * useFactor;\n"
"\n"
"        factor = factor2;\n"
"    }\n"
"\n"
"    // Whatever is left below the last edge belongs to the last segment.\n"
"\n"
"    float4 lastCol = edgemap[colorOfs.x] * edgemap[colorOfs.y];\n"
"\n"
"    float lastFactor = factor * lastCol.a;\n"
"\n"
"    totalAlpha += lastFactor;\n"
"    rgbAcc += lastCol.rgb * lastFactor;\n"
"\n"
"    float4 outColor;\n"
"\n"
"    outColor.a = totalAlpha;\n"
"    outColor.rgb = totalAlpha > 0.0f ? rgbAcc / totalAlpha : float3(0.0f, 0.0f, 0.0f);\n"
"\n"
"    return outColor * input.color;\n"
"}\n"
;


}
