/*=========================================================================

							 >>> WonderGUI <<<

  This file is part of Tord Bärnfors' WonderGUI UI Toolkit and copyright
  Tord Bärnfors, Sweden [mail: first name AT barnfors DOT c_o_m].

								-----------

  The WonderGUI UI Toolkit is free software; you can redistribute
  this file and/or modify it under the terms of the GNU General Public
  License as published by the Free Software Foundation; either
  version 2 of the License, or (at your option) any later version.

								-----------

  The WonderGUI UI Toolkit is also available for use in commercial
  closed source projects under a separate license. Interested parties
  should contact Bärnfors Technology AB [www.barnfors.com] for details.

=========================================================================*/

#include <wg_dx12backend.h>

namespace wg {

const char DX12Backend::g_fillVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;     // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;       // Offset into the color buffer.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_fillPS[] =

"// The tint, shared by all pixel shaders that apply one. wg_dx12shaders.cpp.template\n"
"// puts this file in front of each of them, D3DCompile has no include handler here.\n"
"//\n"
"// A tint block is a run of float4 entries, see TintTools::writeGpuTintBlock():\n"
"//\n"
"//   [0]                 (nLayers, 0, 0, 0)\n"
"//   per layer:\n"
"//     [+0]              (shape, spread, nStops, weight)\n"
"//     [+1]              geometry. Linear: (a, b, c, -) with t = a*x + b*y + c.\n"
"//                                 Radial: (centerX, centerY, invRadiusX, invRadiusY).\n"
"//     [+2]              (1 if stop colors are sRGB encoded else 0, 0, 0, 0)\n"
"//     [+3]...           stop positions, four per entry, unused ones 2.0.\n"
"//     then              one color per stop.\n"
"//\n"
"// Positions are canvas pixels, the device tint is evaluated at pixel centers. Its\n"
"// block lives in the color buffer and the root constants say where, -1 for none.\n"
"\n"
"cbuffer TintInfo : register(b1)\n"
"{\n"
"    int tintOfs;            // Offset of the tint block in the color buffer, -1 for no tint.\n"
"    int3 tintPadding;\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"float tintStopPos(StructuredBuffer<float4> buf, uint posOfs, uint i)\n"
"{\n"
"    float4 v = buf[posOfs + (i >> 2)];\n"
"    uint c = i & 3;\n"
"\n"
"    return c == 0 ? v.x : (c == 1 ? v.y : (c == 2 ? v.z : v.w));\n"
"}\n"
"\n"
"\n"
"float3 tintSRGBToLinear(float3 c)\n"
"{\n"
"    float3 lo = c / 12.92f;\n"
"    float3 hi = pow(abs((c + 0.055f) / 1.055f), 2.4f);        // abs() keeps FXC from warning, c is never negative.\n"
"\n"
"    return lerp(hi, lo, step(c, 0.04045f));\n"
"}\n"
"\n"
"\n"
"float4 evalTintBlock(StructuredBuffer<float4> buf, uint ofs, float2 pos)\n"
"{\n"
"    float4 result = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    uint nLayers = uint(buf[ofs].x);\n"
"    uint p = ofs + 1;\n"
"\n"
"    [loop]\n"
"    for (uint l = 0; l < nLayers; l++)\n"
"    {\n"
"        float4 info = buf[p];\n"
"        float4 geo = buf[p + 1];\n"
"        float srgb = buf[p + 2].x;\n"
"\n"
"        uint nStops = uint(info.z);\n"
"        uint posOfs = p + 3;\n"
"        uint colOfs = posOfs + ((nStops + 3) >> 2);\n"
"\n"
"        [branch]\n"
"        if (nStops > 0)\n"
"        {\n"
"            // Position along the gradient, with spread applied.\n"
"\n"
"            float t;\n"
"\n"
"            if (info.x < 0.5f)\n"
"                t = geo.x * pos.x + geo.y * pos.y + geo.z;\n"
"            else\n"
"                t = length((pos - geo.xy) * geo.zw);\n"
"\n"
"            t = clamp(t, -1e7f, 1e7f);\n"
"\n"
"            uint spread = uint(info.y);\n"
"\n"
"            if (spread == 0)\n"
"                t = saturate(t);\n"
"            else if (spread == 1)\n"
"                t = t - floor(t);\n"
"            else\n"
"            {\n"
"                float r = t - 2.0f * floor(t * 0.5f);\n"
"                t = r > 1.0f ? 2.0f - r : r;\n"
"            }\n"
"\n"
"            // Last stop at or before t. Stops with equal positions make a hard edge.\n"
"\n"
"            int k = -1;\n"
"\n"
"            [loop]\n"
"            for (uint i = 0; i < nStops; i++)\n"
"            {\n"
"                if (tintStopPos(buf, posOfs, i) <= t)\n"
"                    k = int(i);\n"
"            }\n"
"\n"
"            float4 c;\n"
"\n"
"            if (k < 0)\n"
"                c = buf[colOfs];\n"
"            else if (uint(k) == nStops - 1)\n"
"                c = buf[colOfs + uint(k)];\n"
"            else\n"
"            {\n"
"                uint uk = uint(k);\n"
"                float p0 = tintStopPos(buf, posOfs, uk);\n"
"                float p1 = tintStopPos(buf, posOfs, uk + 1);\n"
"\n"
"                c = lerp(buf[colOfs + uk], buf[colOfs + uk + 1], (t - p0) / (p1 - p0));\n"
"            }\n"
"\n"
"            if (srgb > 0.5f)\n"
"                c.rgb = tintSRGBToLinear(c.rgb);\n"
"\n"
"            result += c * info.w;\n"
"        }\n"
"\n"
"        p = colOfs + nStops;\n"
"    }\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"\n"
"// Color of the device tint at a canvas pixel. White when there is no tint.\n"
"\n"
"float4 tintColor(float2 pixelPos)\n"
"{\n"
"    float4 tint = float4(1.0f, 1.0f, 1.0f, 1.0f);\n"
"\n"
"    [branch]\n"
"    if (tintOfs >= 0)\n"
"        tint = evalTintBlock(colors, uint(tintOfs), pixelPos);\n"
"\n"
"    return tint;\n"
"}\n"
"\n"
"// The tint, tintColor() and the colors buffer come from tint.hlsl, which is put\n"
"// in front of this file.\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    return input.color * tintColor(input.position.xy);\n"
"}\n"
;

const char DX12Backend::g_fillAAVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"    float2 textureSize;     // Not used here.\n"
"    uint flags;             // Not used here.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;     // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;       // Offset into the color buffer.\n"
"    uint extrasOfs : EXTRASOFS;     // Offset into the extras buffer.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float4 rect : TEXCOORD0;        // Center of the rectangle in xy, its radius in zw.\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    // The rectangle we are covering, as a center and a radius. Half a pixel is\n"
"    // added to the radius so that a pixel exactly on the edge comes out at full\n"
"    // coverage rather than half.\n"
"\n"
"    output.rect = extras[input.extrasOfs];\n"
"    output.rect.zw += float2(0.5f, 0.5f);\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_fillAAPS[] =

"// The tint, shared by all pixel shaders that apply one. wg_dx12shaders.cpp.template\n"
"// puts this file in front of each of them, D3DCompile has no include handler here.\n"
"//\n"
"// A tint block is a run of float4 entries, see TintTools::writeGpuTintBlock():\n"
"//\n"
"//   [0]                 (nLayers, 0, 0, 0)\n"
"//   per layer:\n"
"//     [+0]              (shape, spread, nStops, weight)\n"
"//     [+1]              geometry. Linear: (a, b, c, -) with t = a*x + b*y + c.\n"
"//                                 Radial: (centerX, centerY, invRadiusX, invRadiusY).\n"
"//     [+2]              (1 if stop colors are sRGB encoded else 0, 0, 0, 0)\n"
"//     [+3]...           stop positions, four per entry, unused ones 2.0.\n"
"//     then              one color per stop.\n"
"//\n"
"// Positions are canvas pixels, the device tint is evaluated at pixel centers. Its\n"
"// block lives in the color buffer and the root constants say where, -1 for none.\n"
"\n"
"cbuffer TintInfo : register(b1)\n"
"{\n"
"    int tintOfs;            // Offset of the tint block in the color buffer, -1 for no tint.\n"
"    int3 tintPadding;\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"float tintStopPos(StructuredBuffer<float4> buf, uint posOfs, uint i)\n"
"{\n"
"    float4 v = buf[posOfs + (i >> 2)];\n"
"    uint c = i & 3;\n"
"\n"
"    return c == 0 ? v.x : (c == 1 ? v.y : (c == 2 ? v.z : v.w));\n"
"}\n"
"\n"
"\n"
"float3 tintSRGBToLinear(float3 c)\n"
"{\n"
"    float3 lo = c / 12.92f;\n"
"    float3 hi = pow(abs((c + 0.055f) / 1.055f), 2.4f);        // abs() keeps FXC from warning, c is never negative.\n"
"\n"
"    return lerp(hi, lo, step(c, 0.04045f));\n"
"}\n"
"\n"
"\n"
"float4 evalTintBlock(StructuredBuffer<float4> buf, uint ofs, float2 pos)\n"
"{\n"
"    float4 result = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    uint nLayers = uint(buf[ofs].x);\n"
"    uint p = ofs + 1;\n"
"\n"
"    [loop]\n"
"    for (uint l = 0; l < nLayers; l++)\n"
"    {\n"
"        float4 info = buf[p];\n"
"        float4 geo = buf[p + 1];\n"
"        float srgb = buf[p + 2].x;\n"
"\n"
"        uint nStops = uint(info.z);\n"
"        uint posOfs = p + 3;\n"
"        uint colOfs = posOfs + ((nStops + 3) >> 2);\n"
"\n"
"        [branch]\n"
"        if (nStops > 0)\n"
"        {\n"
"            // Position along the gradient, with spread applied.\n"
"\n"
"            float t;\n"
"\n"
"            if (info.x < 0.5f)\n"
"                t = geo.x * pos.x + geo.y * pos.y + geo.z;\n"
"            else\n"
"                t = length((pos - geo.xy) * geo.zw);\n"
"\n"
"            t = clamp(t, -1e7f, 1e7f);\n"
"\n"
"            uint spread = uint(info.y);\n"
"\n"
"            if (spread == 0)\n"
"                t = saturate(t);\n"
"            else if (spread == 1)\n"
"                t = t - floor(t);\n"
"            else\n"
"            {\n"
"                float r = t - 2.0f * floor(t * 0.5f);\n"
"                t = r > 1.0f ? 2.0f - r : r;\n"
"            }\n"
"\n"
"            // Last stop at or before t. Stops with equal positions make a hard edge.\n"
"\n"
"            int k = -1;\n"
"\n"
"            [loop]\n"
"            for (uint i = 0; i < nStops; i++)\n"
"            {\n"
"                if (tintStopPos(buf, posOfs, i) <= t)\n"
"                    k = int(i);\n"
"            }\n"
"\n"
"            float4 c;\n"
"\n"
"            if (k < 0)\n"
"                c = buf[colOfs];\n"
"            else if (uint(k) == nStops - 1)\n"
"                c = buf[colOfs + uint(k)];\n"
"            else\n"
"            {\n"
"                uint uk = uint(k);\n"
"                float p0 = tintStopPos(buf, posOfs, uk);\n"
"                float p1 = tintStopPos(buf, posOfs, uk + 1);\n"
"\n"
"                c = lerp(buf[colOfs + uk], buf[colOfs + uk + 1], (t - p0) / (p1 - p0));\n"
"            }\n"
"\n"
"            if (srgb > 0.5f)\n"
"                c.rgb = tintSRGBToLinear(c.rgb);\n"
"\n"
"            result += c * info.w;\n"
"        }\n"
"\n"
"        p = colOfs + nStops;\n"
"    }\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"\n"
"// Color of the device tint at a canvas pixel. White when there is no tint.\n"
"\n"
"float4 tintColor(float2 pixelPos)\n"
"{\n"
"    float4 tint = float4(1.0f, 1.0f, 1.0f, 1.0f);\n"
"\n"
"    [branch]\n"
"    if (tintOfs >= 0)\n"
"        tint = evalTintBlock(colors, uint(tintOfs), pixelPos);\n"
"\n"
"    return tint;\n"
"}\n"
"\n"
"// The tint, tintColor() and the colors buffer come from tint.hlsl, which is put\n"
"// in front of this file.\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float4 rect : TEXCOORD0;        // Center of the rectangle in xy, its radius in zw.\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    // How far this pixel's center is from the center of the rectangle, against\n"
"    // how far it may be before it stops being covered. Anything in between is a\n"
"    // pixel the edge runs through, and gets partial coverage.\n"
"\n"
"    float4 color = input.color;\n"
"\n"
"    float2 middleOfs = abs(input.position.xy - input.rect.xy);\n"
"    float2 alphas = clamp(input.rect.zw - middleOfs, 0.0f, 1.0f);\n"
"\n"
"    color.a = input.color.a * alphas.x * alphas.y;\n"
"\n"
"    return color * tintColor(input.position.xy);\n"
"}\n"
;

const char DX12Backend::g_blitVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"    float2 textureSize;     // Size of blit source, in pixels.\n"
"    uint flags;             // Bit 0: source is alpha only.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;     // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;       // Offset into the color buffer.\n"
"    uint extrasOfs : EXTRASOFS;     // Offset into the extras buffer.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    // First extras entry holds source and destination origin, second one the\n"
"    // transform. Source coordinate is the destination offset run through the\n"
"    // transform, which is how flipping and rotation are handled.\n"
"\n"
"    float4 srcDst = extras[input.extrasOfs];\n"
"    float4 transform = extras[input.extrasOfs + 1];\n"
"\n"
"    float2 src = srcDst.xy;\n"
"    float2 dst = srcDst.zw;\n"
"\n"
"    float2 ofs = input.position - dst;\n"
"\n"
"    output.texUV = float2((src.x + ofs.x * transform.x + ofs.y * transform.z) / textureSize.x,\n"
"                          (src.y + ofs.x * transform.y + ofs.y * transform.w) / textureSize.y);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_blitPS[] =

"// The tint, shared by all pixel shaders that apply one. wg_dx12shaders.cpp.template\n"
"// puts this file in front of each of them, D3DCompile has no include handler here.\n"
"//\n"
"// A tint block is a run of float4 entries, see TintTools::writeGpuTintBlock():\n"
"//\n"
"//   [0]                 (nLayers, 0, 0, 0)\n"
"//   per layer:\n"
"//     [+0]              (shape, spread, nStops, weight)\n"
"//     [+1]              geometry. Linear: (a, b, c, -) with t = a*x + b*y + c.\n"
"//                                 Radial: (centerX, centerY, invRadiusX, invRadiusY).\n"
"//     [+2]              (1 if stop colors are sRGB encoded else 0, 0, 0, 0)\n"
"//     [+3]...           stop positions, four per entry, unused ones 2.0.\n"
"//     then              one color per stop.\n"
"//\n"
"// Positions are canvas pixels, the device tint is evaluated at pixel centers. Its\n"
"// block lives in the color buffer and the root constants say where, -1 for none.\n"
"\n"
"cbuffer TintInfo : register(b1)\n"
"{\n"
"    int tintOfs;            // Offset of the tint block in the color buffer, -1 for no tint.\n"
"    int3 tintPadding;\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"float tintStopPos(StructuredBuffer<float4> buf, uint posOfs, uint i)\n"
"{\n"
"    float4 v = buf[posOfs + (i >> 2)];\n"
"    uint c = i & 3;\n"
"\n"
"    return c == 0 ? v.x : (c == 1 ? v.y : (c == 2 ? v.z : v.w));\n"
"}\n"
"\n"
"\n"
"float3 tintSRGBToLinear(float3 c)\n"
"{\n"
"    float3 lo = c / 12.92f;\n"
"    float3 hi = pow(abs((c + 0.055f) / 1.055f), 2.4f);        // abs() keeps FXC from warning, c is never negative.\n"
"\n"
"    return lerp(hi, lo, step(c, 0.04045f));\n"
"}\n"
"\n"
"\n"
"float4 evalTintBlock(StructuredBuffer<float4> buf, uint ofs, float2 pos)\n"
"{\n"
"    float4 result = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    uint nLayers = uint(buf[ofs].x);\n"
"    uint p = ofs + 1;\n"
"\n"
"    [loop]\n"
"    for (uint l = 0; l < nLayers; l++)\n"
"    {\n"
"        float4 info = buf[p];\n"
"        float4 geo = buf[p + 1];\n"
"        float srgb = buf[p + 2].x;\n"
"\n"
"        uint nStops = uint(info.z);\n"
"        uint posOfs = p + 3;\n"
"        uint colOfs = posOfs + ((nStops + 3) >> 2);\n"
"\n"
"        [branch]\n"
"        if (nStops > 0)\n"
"        {\n"
"            // Position along the gradient, with spread applied.\n"
"\n"
"            float t;\n"
"\n"
"            if (info.x < 0.5f)\n"
"                t = geo.x * pos.x + geo.y * pos.y + geo.z;\n"
"            else\n"
"                t = length((pos - geo.xy) * geo.zw);\n"
"\n"
"            t = clamp(t, -1e7f, 1e7f);\n"
"\n"
"            uint spread = uint(info.y);\n"
"\n"
"            if (spread == 0)\n"
"                t = saturate(t);\n"
"            else if (spread == 1)\n"
"                t = t - floor(t);\n"
"            else\n"
"            {\n"
"                float r = t - 2.0f * floor(t * 0.5f);\n"
"                t = r > 1.0f ? 2.0f - r : r;\n"
"            }\n"
"\n"
"            // Last stop at or before t. Stops with equal positions make a hard edge.\n"
"\n"
"            int k = -1;\n"
"\n"
"            [loop]\n"
"            for (uint i = 0; i < nStops; i++)\n"
"            {\n"
"                if (tintStopPos(buf, posOfs, i) <= t)\n"
"                    k = int(i);\n"
"            }\n"
"\n"
"            float4 c;\n"
"\n"
"            if (k < 0)\n"
"                c = buf[colOfs];\n"
"            else if (uint(k) == nStops - 1)\n"
"                c = buf[colOfs + uint(k)];\n"
"            else\n"
"            {\n"
"                uint uk = uint(k);\n"
"                float p0 = tintStopPos(buf, posOfs, uk);\n"
"                float p1 = tintStopPos(buf, posOfs, uk + 1);\n"
"\n"
"                c = lerp(buf[colOfs + uk], buf[colOfs + uk + 1], (t - p0) / (p1 - p0));\n"
"            }\n"
"\n"
"            if (srgb > 0.5f)\n"
"                c.rgb = tintSRGBToLinear(c.rgb);\n"
"\n"
"            result += c * info.w;\n"
"        }\n"
"\n"
"        p = colOfs + nStops;\n"
"    }\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"\n"
"// Color of the device tint at a canvas pixel. White when there is no tint.\n"
"\n"
"float4 tintColor(float2 pixelPos)\n"
"{\n"
"    float4 tint = float4(1.0f, 1.0f, 1.0f, 1.0f);\n"
"\n"
"    [branch]\n"
"    if (tintOfs >= 0)\n"
"        tint = evalTintBlock(colors, uint(tintOfs), pixelPos);\n"
"\n"
"    return tint;\n"
"}\n"
"\n"
"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;\n"
"    float2 textureSize;\n"
"    uint flags;             // Bit 0: source is alpha only.\n"
"};\n"
"\n"
"// The tint, tintColor() and the colors buffer come from tint.hlsl, which is put\n"
"// in front of this file.\n"
"\n"
"\n"
"Texture2D blitSource : register(t2);\n"
"SamplerState blitSampler : register(s0);\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    float4 texel = blitSource.Sample(blitSampler, input.texUV);\n"
"\n"
"    // An alpha only source has no color of its own, it just modulates the tint.\n"
"\n"
"    if ((flags & 1) != 0)\n"
"    {\n"
"        float4 color = input.color;\n"
"        color.a *= texel.a;\n"
"        return color * tintColor(input.position.xy);\n"
"    }\n"
"\n"
"    return texel * input.color * tintColor(input.position.xy);\n"
"}\n"
;

const char DX12Backend::g_blurPS[] =

"// The tint, shared by all pixel shaders that apply one. wg_dx12shaders.cpp.template\n"
"// puts this file in front of each of them, D3DCompile has no include handler here.\n"
"//\n"
"// A tint block is a run of float4 entries, see TintTools::writeGpuTintBlock():\n"
"//\n"
"//   [0]                 (nLayers, 0, 0, 0)\n"
"//   per layer:\n"
"//     [+0]              (shape, spread, nStops, weight)\n"
"//     [+1]              geometry. Linear: (a, b, c, -) with t = a*x + b*y + c.\n"
"//                                 Radial: (centerX, centerY, invRadiusX, invRadiusY).\n"
"//     [+2]              (1 if stop colors are sRGB encoded else 0, 0, 0, 0)\n"
"//     [+3]...           stop positions, four per entry, unused ones 2.0.\n"
"//     then              one color per stop.\n"
"//\n"
"// Positions are canvas pixels, the device tint is evaluated at pixel centers. Its\n"
"// block lives in the color buffer and the root constants say where, -1 for none.\n"
"\n"
"cbuffer TintInfo : register(b1)\n"
"{\n"
"    int tintOfs;            // Offset of the tint block in the color buffer, -1 for no tint.\n"
"    int3 tintPadding;\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"float tintStopPos(StructuredBuffer<float4> buf, uint posOfs, uint i)\n"
"{\n"
"    float4 v = buf[posOfs + (i >> 2)];\n"
"    uint c = i & 3;\n"
"\n"
"    return c == 0 ? v.x : (c == 1 ? v.y : (c == 2 ? v.z : v.w));\n"
"}\n"
"\n"
"\n"
"float3 tintSRGBToLinear(float3 c)\n"
"{\n"
"    float3 lo = c / 12.92f;\n"
"    float3 hi = pow(abs((c + 0.055f) / 1.055f), 2.4f);        // abs() keeps FXC from warning, c is never negative.\n"
"\n"
"    return lerp(hi, lo, step(c, 0.04045f));\n"
"}\n"
"\n"
"\n"
"float4 evalTintBlock(StructuredBuffer<float4> buf, uint ofs, float2 pos)\n"
"{\n"
"    float4 result = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    uint nLayers = uint(buf[ofs].x);\n"
"    uint p = ofs + 1;\n"
"\n"
"    [loop]\n"
"    for (uint l = 0; l < nLayers; l++)\n"
"    {\n"
"        float4 info = buf[p];\n"
"        float4 geo = buf[p + 1];\n"
"        float srgb = buf[p + 2].x;\n"
"\n"
"        uint nStops = uint(info.z);\n"
"        uint posOfs = p + 3;\n"
"        uint colOfs = posOfs + ((nStops + 3) >> 2);\n"
"\n"
"        [branch]\n"
"        if (nStops > 0)\n"
"        {\n"
"            // Position along the gradient, with spread applied.\n"
"\n"
"            float t;\n"
"\n"
"            if (info.x < 0.5f)\n"
"                t = geo.x * pos.x + geo.y * pos.y + geo.z;\n"
"            else\n"
"                t = length((pos - geo.xy) * geo.zw);\n"
"\n"
"            t = clamp(t, -1e7f, 1e7f);\n"
"\n"
"            uint spread = uint(info.y);\n"
"\n"
"            if (spread == 0)\n"
"                t = saturate(t);\n"
"            else if (spread == 1)\n"
"                t = t - floor(t);\n"
"            else\n"
"            {\n"
"                float r = t - 2.0f * floor(t * 0.5f);\n"
"                t = r > 1.0f ? 2.0f - r : r;\n"
"            }\n"
"\n"
"            // Last stop at or before t. Stops with equal positions make a hard edge.\n"
"\n"
"            int k = -1;\n"
"\n"
"            [loop]\n"
"            for (uint i = 0; i < nStops; i++)\n"
"            {\n"
"                if (tintStopPos(buf, posOfs, i) <= t)\n"
"                    k = int(i);\n"
"            }\n"
"\n"
"            float4 c;\n"
"\n"
"            if (k < 0)\n"
"                c = buf[colOfs];\n"
"            else if (uint(k) == nStops - 1)\n"
"                c = buf[colOfs + uint(k)];\n"
"            else\n"
"            {\n"
"                uint uk = uint(k);\n"
"                float p0 = tintStopPos(buf, posOfs, uk);\n"
"                float p1 = tintStopPos(buf, posOfs, uk + 1);\n"
"\n"
"                c = lerp(buf[colOfs + uk], buf[colOfs + uk + 1], (t - p0) / (p1 - p0));\n"
"            }\n"
"\n"
"            if (srgb > 0.5f)\n"
"                c.rgb = tintSRGBToLinear(c.rgb);\n"
"\n"
"            result += c * info.w;\n"
"        }\n"
"\n"
"        p = colOfs + nStops;\n"
"    }\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"\n"
"// Color of the device tint at a canvas pixel. White when there is no tint.\n"
"\n"
"float4 tintColor(float2 pixelPos)\n"
"{\n"
"    float4 tint = float4(1.0f, 1.0f, 1.0f, 1.0f);\n"
"\n"
"    [branch]\n"
"    if (tintOfs >= 0)\n"
"        tint = evalTintBlock(colors, uint(tintOfs), pixelPos);\n"
"\n"
"    return tint;\n"
"}\n"
"\n"
"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // Not used here.\n"
"    float2 textureSize;     // Not used here, the vertex shader has already used it.\n"
"    uint flags;             // Not used here.\n"
"    uint blurOfs;           // Where our 9 color matrices and 9 offsets start in extras.\n"
"};\n"
"\n"
"// The tint, tintColor() and the colors buffer come from tint.hlsl, which is put\n"
"// in front of this file.\n"
"\n"
"\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"Texture2D blitSource : register(t2);\n"
"SamplerState blitSampler : register(s0);\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    // An alpha only source has no color to blur, so its alpha is blurred instead\n"
"    // and the tint supplies the color. The red row of the matrix is used as the\n"
"    // weight, the three rows being the same for an ordinary brush.\n"
"\n"
"    if ((flags & 1u) != 0u)\n"
"    {\n"
"        float alpha = 0.0f;\n"
"\n"
"        [unroll]\n"
"        for (uint j = 0u; j < 9u; j++)\n"
"        {\n"
"            float2 ofs = extras[blurOfs + 9u + j].xy;\n"
"\n"
"            alpha += blitSource.Sample(blitSampler, input.texUV + ofs).a * extras[blurOfs + j].x;\n"
"        }\n"
"\n"
"        float4 alphaColor = input.color;\n"
"        alphaColor.a *= alpha;\n"
"\n"
"        return alphaColor * tintColor(input.position.xy);\n"
"    }\n"
"\n"
"    // Nine taps around this one, each weighted per channel by its own row of the\n"
"    // brush's color matrix. The offsets are in texture coordinates, worked out\n"
"    // from the blur radius and the size of the source.\n"
"\n"
"    float4 color = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    [unroll]\n"
"    for (uint i = 0u; i < 9u; i++)\n"
"    {\n"
"        float2 ofs = extras[blurOfs + 9u + i].xy;\n"
"\n"
"        color += blitSource.Sample(blitSampler, input.texUV + ofs) * extras[blurOfs + i];\n"
"    }\n"
"\n"
"    // A blur has no alpha of its own. What comes out is opaque, and the tint or\n"
"    // tintmap is what decides how much of it reaches the canvas.\n"
"\n"
"    color.a = 1.0f;\n"
"\n"
"    return color * input.color * tintColor(input.position.xy);\n"
"}\n"
;

const char DX12Backend::g_paletteBlitPS[] =

"// The tint, shared by all pixel shaders that apply one. wg_dx12shaders.cpp.template\n"
"// puts this file in front of each of them, D3DCompile has no include handler here.\n"
"//\n"
"// A tint block is a run of float4 entries, see TintTools::writeGpuTintBlock():\n"
"//\n"
"//   [0]                 (nLayers, 0, 0, 0)\n"
"//   per layer:\n"
"//     [+0]              (shape, spread, nStops, weight)\n"
"//     [+1]              geometry. Linear: (a, b, c, -) with t = a*x + b*y + c.\n"
"//                                 Radial: (centerX, centerY, invRadiusX, invRadiusY).\n"
"//     [+2]              (1 if stop colors are sRGB encoded else 0, 0, 0, 0)\n"
"//     [+3]...           stop positions, four per entry, unused ones 2.0.\n"
"//     then              one color per stop.\n"
"//\n"
"// Positions are canvas pixels, the device tint is evaluated at pixel centers. Its\n"
"// block lives in the color buffer and the root constants say where, -1 for none.\n"
"\n"
"cbuffer TintInfo : register(b1)\n"
"{\n"
"    int tintOfs;            // Offset of the tint block in the color buffer, -1 for no tint.\n"
"    int3 tintPadding;\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"float tintStopPos(StructuredBuffer<float4> buf, uint posOfs, uint i)\n"
"{\n"
"    float4 v = buf[posOfs + (i >> 2)];\n"
"    uint c = i & 3;\n"
"\n"
"    return c == 0 ? v.x : (c == 1 ? v.y : (c == 2 ? v.z : v.w));\n"
"}\n"
"\n"
"\n"
"float3 tintSRGBToLinear(float3 c)\n"
"{\n"
"    float3 lo = c / 12.92f;\n"
"    float3 hi = pow(abs((c + 0.055f) / 1.055f), 2.4f);        // abs() keeps FXC from warning, c is never negative.\n"
"\n"
"    return lerp(hi, lo, step(c, 0.04045f));\n"
"}\n"
"\n"
"\n"
"float4 evalTintBlock(StructuredBuffer<float4> buf, uint ofs, float2 pos)\n"
"{\n"
"    float4 result = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    uint nLayers = uint(buf[ofs].x);\n"
"    uint p = ofs + 1;\n"
"\n"
"    [loop]\n"
"    for (uint l = 0; l < nLayers; l++)\n"
"    {\n"
"        float4 info = buf[p];\n"
"        float4 geo = buf[p + 1];\n"
"        float srgb = buf[p + 2].x;\n"
"\n"
"        uint nStops = uint(info.z);\n"
"        uint posOfs = p + 3;\n"
"        uint colOfs = posOfs + ((nStops + 3) >> 2);\n"
"\n"
"        [branch]\n"
"        if (nStops > 0)\n"
"        {\n"
"            // Position along the gradient, with spread applied.\n"
"\n"
"            float t;\n"
"\n"
"            if (info.x < 0.5f)\n"
"                t = geo.x * pos.x + geo.y * pos.y + geo.z;\n"
"            else\n"
"                t = length((pos - geo.xy) * geo.zw);\n"
"\n"
"            t = clamp(t, -1e7f, 1e7f);\n"
"\n"
"            uint spread = uint(info.y);\n"
"\n"
"            if (spread == 0)\n"
"                t = saturate(t);\n"
"            else if (spread == 1)\n"
"                t = t - floor(t);\n"
"            else\n"
"            {\n"
"                float r = t - 2.0f * floor(t * 0.5f);\n"
"                t = r > 1.0f ? 2.0f - r : r;\n"
"            }\n"
"\n"
"            // Last stop at or before t. Stops with equal positions make a hard edge.\n"
"\n"
"            int k = -1;\n"
"\n"
"            [loop]\n"
"            for (uint i = 0; i < nStops; i++)\n"
"            {\n"
"                if (tintStopPos(buf, posOfs, i) <= t)\n"
"                    k = int(i);\n"
"            }\n"
"\n"
"            float4 c;\n"
"\n"
"            if (k < 0)\n"
"                c = buf[colOfs];\n"
"            else if (uint(k) == nStops - 1)\n"
"                c = buf[colOfs + uint(k)];\n"
"            else\n"
"            {\n"
"                uint uk = uint(k);\n"
"                float p0 = tintStopPos(buf, posOfs, uk);\n"
"                float p1 = tintStopPos(buf, posOfs, uk + 1);\n"
"\n"
"                c = lerp(buf[colOfs + uk], buf[colOfs + uk + 1], (t - p0) / (p1 - p0));\n"
"            }\n"
"\n"
"            if (srgb > 0.5f)\n"
"                c.rgb = tintSRGBToLinear(c.rgb);\n"
"\n"
"            result += c * info.w;\n"
"        }\n"
"\n"
"        p = colOfs + nStops;\n"
"    }\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"\n"
"// Color of the device tint at a canvas pixel. White when there is no tint.\n"
"\n"
"float4 tintColor(float2 pixelPos)\n"
"{\n"
"    float4 tint = float4(1.0f, 1.0f, 1.0f, 1.0f);\n"
"\n"
"    [branch]\n"
"    if (tintOfs >= 0)\n"
"        tint = evalTintBlock(colors, uint(tintOfs), pixelPos);\n"
"\n"
"    return tint;\n"
"}\n"
"\n"
"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // Not used here.\n"
"    float2 textureSize;     // Size of blit source, in pixels.\n"
"    uint flags;             // Bit 1: bilinear. Bit 2: tiling.\n"
"    uint blurOfs;           // Where a blur's 9 color matrices and 9 offsets start in extras.\n"
"};\n"
"\n"
"// The tint, tintColor() and the colors buffer come from tint.hlsl, which is put\n"
"// in front of this file.\n"
"\n"
"\n"
"// A palette based source is a texture of 8 or 16 bit indexes and a palette of\n"
"// colors already converted to linear. The palette lookup has to come before any\n"
"// filtering, so we fetch texels ourselves rather than going through a sampler,\n"
"// and do what the sampler would have done: wrap or clamp at the edges, and for\n"
"// a bilinear surface blend the four texels around us.\n"
"//\n"
"// The palette's first entry holds its capacity, the colors follow. An index\n"
"// beyond the palette is clamped to its last entry rather than read from\n"
"// whatever lies past the end of the buffer.\n"
"\n"
"Texture2D<uint> blitSource : register(t2);\n"
"StructuredBuffer<float4> palette : register(t3);\n"
"\n"
"\n"
"float4 paletteTexel(int2 texel)\n"
"{\n"
"    int2 size = int2(textureSize);\n"
"\n"
"    if ((flags & 4u) != 0u)\n"
"    {\n"
"        // Wrap. Done in unsigned, since the compiler warns about signed modulus\n"
"        // and we treat warnings as errors. A texel left of or above the source\n"
"        // wraps from the other side.\n"
"\n"
"        uint2 usize = uint2(size);\n"
"        uint2 rest = uint2(abs(texel)) % usize;\n"
"\n"
"        texel.x = (texel.x >= 0 || rest.x == 0u) ? int(rest.x) : int(usize.x - rest.x);\n"
"        texel.y = (texel.y >= 0 || rest.y == 0u) ? int(rest.y) : int(usize.y - rest.y);\n"
"    }\n"
"    else\n"
"        texel = clamp(texel, int2(0, 0), size - int2(1, 1));\n"
"\n"
"    uint index = blitSource.Load(int3(texel, 0));\n"
"    uint capacity = uint(palette[0].x);\n"
"\n"
"    return palette[min(index, capacity - 1u) + 1u];\n"
"}\n"
"\n"
"\n"
"float4 samplePalette(float2 uv)\n"
"{\n"
"    // One return at the end: FXC takes an early return out of a function to\n"
"    // mean the result may be left uninitialized (X4000), and warnings are\n"
"    // errors for us.\n"
"\n"
"    float2 pos = uv * textureSize;\n"
"    float4 color;\n"
"\n"
"    if ((flags & 2u) != 0u)\n"
"    {\n"
"        // Bilinear. Texel centers are at .5, so the four texels around us start\n"
"        // half a texel up and to the left.\n"
"\n"
"        float2 base = pos - 0.5f;\n"
"        float2 baseFloor = floor(base);\n"
"        float2 weight = base - baseFloor;\n"
"        int2 texel = int2(baseFloor);\n"
"\n"
"        float4 c00 = paletteTexel(texel);\n"
"        float4 c10 = paletteTexel(texel + int2(1, 0));\n"
"        float4 c01 = paletteTexel(texel + int2(0, 1));\n"
"        float4 c11 = paletteTexel(texel + int2(1, 1));\n"
"\n"
"        color = lerp(lerp(c00, c10, weight.x), lerp(c01, c11, weight.x), weight.y);\n"
"    }\n"
"    else\n"
"    {\n"
"        // Nearest. A pixel lined up with the source lands exactly on a texel\n"
"        // edge, where rounding could tip it into the texel before. The sampler\n"
"        // snaps to a fraction of a texel for the same reason, so we nudge by as\n"
"        // much.\n"
"\n"
"        color = paletteTexel(int2(floor(pos + 1.0f / 256.0f)));\n"
"    }\n"
"\n"
"    return color;\n"
"}\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    return samplePalette(input.texUV) * input.color * tintColor(input.position.xy);\n"
"}\n"
;

const char DX12Backend::g_paletteBlurPS[] =

"// The tint, shared by all pixel shaders that apply one. wg_dx12shaders.cpp.template\n"
"// puts this file in front of each of them, D3DCompile has no include handler here.\n"
"//\n"
"// A tint block is a run of float4 entries, see TintTools::writeGpuTintBlock():\n"
"//\n"
"//   [0]                 (nLayers, 0, 0, 0)\n"
"//   per layer:\n"
"//     [+0]              (shape, spread, nStops, weight)\n"
"//     [+1]              geometry. Linear: (a, b, c, -) with t = a*x + b*y + c.\n"
"//                                 Radial: (centerX, centerY, invRadiusX, invRadiusY).\n"
"//     [+2]              (1 if stop colors are sRGB encoded else 0, 0, 0, 0)\n"
"//     [+3]...           stop positions, four per entry, unused ones 2.0.\n"
"//     then              one color per stop.\n"
"//\n"
"// Positions are canvas pixels, the device tint is evaluated at pixel centers. Its\n"
"// block lives in the color buffer and the root constants say where, -1 for none.\n"
"\n"
"cbuffer TintInfo : register(b1)\n"
"{\n"
"    int tintOfs;            // Offset of the tint block in the color buffer, -1 for no tint.\n"
"    int3 tintPadding;\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"float tintStopPos(StructuredBuffer<float4> buf, uint posOfs, uint i)\n"
"{\n"
"    float4 v = buf[posOfs + (i >> 2)];\n"
"    uint c = i & 3;\n"
"\n"
"    return c == 0 ? v.x : (c == 1 ? v.y : (c == 2 ? v.z : v.w));\n"
"}\n"
"\n"
"\n"
"float3 tintSRGBToLinear(float3 c)\n"
"{\n"
"    float3 lo = c / 12.92f;\n"
"    float3 hi = pow(abs((c + 0.055f) / 1.055f), 2.4f);        // abs() keeps FXC from warning, c is never negative.\n"
"\n"
"    return lerp(hi, lo, step(c, 0.04045f));\n"
"}\n"
"\n"
"\n"
"float4 evalTintBlock(StructuredBuffer<float4> buf, uint ofs, float2 pos)\n"
"{\n"
"    float4 result = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    uint nLayers = uint(buf[ofs].x);\n"
"    uint p = ofs + 1;\n"
"\n"
"    [loop]\n"
"    for (uint l = 0; l < nLayers; l++)\n"
"    {\n"
"        float4 info = buf[p];\n"
"        float4 geo = buf[p + 1];\n"
"        float srgb = buf[p + 2].x;\n"
"\n"
"        uint nStops = uint(info.z);\n"
"        uint posOfs = p + 3;\n"
"        uint colOfs = posOfs + ((nStops + 3) >> 2);\n"
"\n"
"        [branch]\n"
"        if (nStops > 0)\n"
"        {\n"
"            // Position along the gradient, with spread applied.\n"
"\n"
"            float t;\n"
"\n"
"            if (info.x < 0.5f)\n"
"                t = geo.x * pos.x + geo.y * pos.y + geo.z;\n"
"            else\n"
"                t = length((pos - geo.xy) * geo.zw);\n"
"\n"
"            t = clamp(t, -1e7f, 1e7f);\n"
"\n"
"            uint spread = uint(info.y);\n"
"\n"
"            if (spread == 0)\n"
"                t = saturate(t);\n"
"            else if (spread == 1)\n"
"                t = t - floor(t);\n"
"            else\n"
"            {\n"
"                float r = t - 2.0f * floor(t * 0.5f);\n"
"                t = r > 1.0f ? 2.0f - r : r;\n"
"            }\n"
"\n"
"            // Last stop at or before t. Stops with equal positions make a hard edge.\n"
"\n"
"            int k = -1;\n"
"\n"
"            [loop]\n"
"            for (uint i = 0; i < nStops; i++)\n"
"            {\n"
"                if (tintStopPos(buf, posOfs, i) <= t)\n"
"                    k = int(i);\n"
"            }\n"
"\n"
"            float4 c;\n"
"\n"
"            if (k < 0)\n"
"                c = buf[colOfs];\n"
"            else if (uint(k) == nStops - 1)\n"
"                c = buf[colOfs + uint(k)];\n"
"            else\n"
"            {\n"
"                uint uk = uint(k);\n"
"                float p0 = tintStopPos(buf, posOfs, uk);\n"
"                float p1 = tintStopPos(buf, posOfs, uk + 1);\n"
"\n"
"                c = lerp(buf[colOfs + uk], buf[colOfs + uk + 1], (t - p0) / (p1 - p0));\n"
"            }\n"
"\n"
"            if (srgb > 0.5f)\n"
"                c.rgb = tintSRGBToLinear(c.rgb);\n"
"\n"
"            result += c * info.w;\n"
"        }\n"
"\n"
"        p = colOfs + nStops;\n"
"    }\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"\n"
"// Color of the device tint at a canvas pixel. White when there is no tint.\n"
"\n"
"float4 tintColor(float2 pixelPos)\n"
"{\n"
"    float4 tint = float4(1.0f, 1.0f, 1.0f, 1.0f);\n"
"\n"
"    [branch]\n"
"    if (tintOfs >= 0)\n"
"        tint = evalTintBlock(colors, uint(tintOfs), pixelPos);\n"
"\n"
"    return tint;\n"
"}\n"
"\n"
"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // Not used here.\n"
"    float2 textureSize;     // Size of blit source, in pixels.\n"
"    uint flags;             // Bit 1: bilinear. Bit 2: tiling.\n"
"    uint blurOfs;           // Where a blur's 9 color matrices and 9 offsets start in extras.\n"
"};\n"
"\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"// The tint, tintColor() and the colors buffer come from tint.hlsl, which is put\n"
"// in front of this file.\n"
"\n"
"\n"
"// A palette based source is a texture of 8 or 16 bit indexes and a palette of\n"
"// colors already converted to linear. The palette lookup has to come before any\n"
"// filtering, so we fetch texels ourselves rather than going through a sampler,\n"
"// and do what the sampler would have done: wrap or clamp at the edges, and for\n"
"// a bilinear surface blend the four texels around us.\n"
"//\n"
"// The palette's first entry holds its capacity, the colors follow. An index\n"
"// beyond the palette is clamped to its last entry rather than read from\n"
"// whatever lies past the end of the buffer.\n"
"\n"
"Texture2D<uint> blitSource : register(t2);\n"
"StructuredBuffer<float4> palette : register(t3);\n"
"\n"
"\n"
"float4 paletteTexel(int2 texel)\n"
"{\n"
"    int2 size = int2(textureSize);\n"
"\n"
"    if ((flags & 4u) != 0u)\n"
"    {\n"
"        // Wrap. Done in unsigned, since the compiler warns about signed modulus\n"
"        // and we treat warnings as errors. A texel left of or above the source\n"
"        // wraps from the other side.\n"
"\n"
"        uint2 usize = uint2(size);\n"
"        uint2 rest = uint2(abs(texel)) % usize;\n"
"\n"
"        texel.x = (texel.x >= 0 || rest.x == 0u) ? int(rest.x) : int(usize.x - rest.x);\n"
"        texel.y = (texel.y >= 0 || rest.y == 0u) ? int(rest.y) : int(usize.y - rest.y);\n"
"    }\n"
"    else\n"
"        texel = clamp(texel, int2(0, 0), size - int2(1, 1));\n"
"\n"
"    uint index = blitSource.Load(int3(texel, 0));\n"
"    uint capacity = uint(palette[0].x);\n"
"\n"
"    return palette[min(index, capacity - 1u) + 1u];\n"
"}\n"
"\n"
"\n"
"float4 samplePalette(float2 uv)\n"
"{\n"
"    // One return at the end: FXC takes an early return out of a function to\n"
"    // mean the result may be left uninitialized (X4000), and warnings are\n"
"    // errors for us.\n"
"\n"
"    float2 pos = uv * textureSize;\n"
"    float4 color;\n"
"\n"
"    if ((flags & 2u) != 0u)\n"
"    {\n"
"        // Bilinear. Texel centers are at .5, so the four texels around us start\n"
"        // half a texel up and to the left.\n"
"\n"
"        float2 base = pos - 0.5f;\n"
"        float2 baseFloor = floor(base);\n"
"        float2 weight = base - baseFloor;\n"
"        int2 texel = int2(baseFloor);\n"
"\n"
"        float4 c00 = paletteTexel(texel);\n"
"        float4 c10 = paletteTexel(texel + int2(1, 0));\n"
"        float4 c01 = paletteTexel(texel + int2(0, 1));\n"
"        float4 c11 = paletteTexel(texel + int2(1, 1));\n"
"\n"
"        color = lerp(lerp(c00, c10, weight.x), lerp(c01, c11, weight.x), weight.y);\n"
"    }\n"
"    else\n"
"    {\n"
"        // Nearest. A pixel lined up with the source lands exactly on a texel\n"
"        // edge, where rounding could tip it into the texel before. The sampler\n"
"        // snaps to a fraction of a texel for the same reason, so we nudge by as\n"
"        // much.\n"
"\n"
"        color = paletteTexel(int2(floor(pos + 1.0f / 256.0f)));\n"
"    }\n"
"\n"
"    return color;\n"
"}\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    // As ps_blur, but with each tap looked up in the palette.\n"
"\n"
"    float4 color = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    [unroll]\n"
"    for (uint i = 0u; i < 9u; i++)\n"
"    {\n"
"        float2 ofs = extras[blurOfs + 9u + i].xy;\n"
"\n"
"        color += samplePalette(input.texUV + ofs) * extras[blurOfs + i];\n"
"    }\n"
"\n"
"    color.a = 1.0f;\n"
"\n"
"    return color * input.color * tintColor(input.position.xy);\n"
"}\n"
;

const char DX12Backend::g_lineVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"    float2 textureSize;     // Not used here.\n"
"    uint flags;             // Not used here.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;     // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;       // Offset into the color buffer.\n"
"    uint extrasOfs : EXTRASOFS;     // Offset into the extras buffer.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float4 lineInfo : TEXCOORD0;    // Offset, half width, slope, and whether it is steep.\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    // The line itself, which every vertex of the quad carries unchanged. The\n"
"    // pixel shader works out how much of each pixel the line covers.\n"
"\n"
"    output.lineInfo = extras[input.extrasOfs];\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_linePS[] =

"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float4 lineInfo : TEXCOORD0;    // Offset, half width, slope, and whether it is steep.\n"
"};\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    float s = input.lineInfo.x;\n"
"    float w = input.lineInfo.y;\n"
"    float slope = input.lineInfo.z;\n"
"\n"
"    // A steep line runs mainly vertically, so x and y swap roles. Carrying it as\n"
"    // a number rather than a branch keeps the maths to one expression.\n"
"\n"
"    float ifSteep = input.lineInfo.w;\n"
"    float ifMild = 1.0f - ifSteep;\n"
"\n"
"    float2 pos = input.position.xy;\n"
"\n"
"    float along = pos.x * ifMild + pos.y * ifSteep;\n"
"    float across = pos.x * ifSteep + pos.y * ifMild;\n"
"\n"
"    // Distance from the center of the line, against its half width. A pixel\n"
"    // further away than that is outside the line, one closer is fully inside.\n"
"\n"
"    float4 color = input.color;\n"
"\n"
"    color.a = input.color.a * clamp(w - abs(across - s - along * slope), 0.0f, 1.0f);\n"
"\n"
"    return color;\n"
"}\n"
;

const char DX12Backend::g_segmentsVS[] =

"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // 2/canvasWidth, 2/canvasHeight, in pixels.\n"
"    float2 textureSize;     // Not used here.\n"
"    uint flags;             // Not used here.\n"
"    uint blurOfs;           // Not used here.\n"
"    uint edgemapEdges;      // Not used here.\n"
"    uint edgemapPitch;      // Not used here.\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"StructuredBuffer<float4> extras : register(t1);\n"
"\n"
"\n"
"struct VS_INPUT\n"
"{\n"
"    float2 position : POSITION;         // Canvas pixels, origin top left.\n"
"    uint colorOfs : COLOROFS;           // Offset into the color buffer.\n"
"    uint extrasOfs : EXTRASOFS;         // Offset into the extras buffer.\n"
"    float2 texUV : TEXCOORD0;           // Column in x, distance down the column in y.\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"    nointerpolation uint2 segColorsOfs : TEXCOORD1;    // Flat colors and tint table in the edgemap buffer.\n"
"};\n"
"\n"
"\n"
"VS_OUTPUT main(VS_INPUT input)\n"
"{\n"
"    VS_OUTPUT output;\n"
"\n"
"    // Canvas pixels to clip space. Y is flipped, in clip space it points up.\n"
"\n"
"    output.position = float4(input.position.x * canvasScale.x - 1.0f,\n"
"                             1.0f - input.position.y * canvasScale.y,\n"
"                             0.0f, 1.0f);\n"
"\n"
"    output.color = colors[input.colorOfs];\n"
"\n"
"    output.texUV = input.texUV;\n"
"\n"
"    // Where the edgemap's flat segment colors and tint table are, the same for\n"
"    // the whole edgemap.\n"
"\n"
"    output.segColorsOfs = uint2(extras[input.extrasOfs].xy);\n"
"\n"
"    return output;\n"
"}\n"
;

const char DX12Backend::g_segmentsPS[] =

"// The tint, shared by all pixel shaders that apply one. wg_dx12shaders.cpp.template\n"
"// puts this file in front of each of them, D3DCompile has no include handler here.\n"
"//\n"
"// A tint block is a run of float4 entries, see TintTools::writeGpuTintBlock():\n"
"//\n"
"//   [0]                 (nLayers, 0, 0, 0)\n"
"//   per layer:\n"
"//     [+0]              (shape, spread, nStops, weight)\n"
"//     [+1]              geometry. Linear: (a, b, c, -) with t = a*x + b*y + c.\n"
"//                                 Radial: (centerX, centerY, invRadiusX, invRadiusY).\n"
"//     [+2]              (1 if stop colors are sRGB encoded else 0, 0, 0, 0)\n"
"//     [+3]...           stop positions, four per entry, unused ones 2.0.\n"
"//     then              one color per stop.\n"
"//\n"
"// Positions are canvas pixels, the device tint is evaluated at pixel centers. Its\n"
"// block lives in the color buffer and the root constants say where, -1 for none.\n"
"\n"
"cbuffer TintInfo : register(b1)\n"
"{\n"
"    int tintOfs;            // Offset of the tint block in the color buffer, -1 for no tint.\n"
"    int3 tintPadding;\n"
"};\n"
"\n"
"StructuredBuffer<float4> colors : register(t0);\n"
"\n"
"\n"
"float tintStopPos(StructuredBuffer<float4> buf, uint posOfs, uint i)\n"
"{\n"
"    float4 v = buf[posOfs + (i >> 2)];\n"
"    uint c = i & 3;\n"
"\n"
"    return c == 0 ? v.x : (c == 1 ? v.y : (c == 2 ? v.z : v.w));\n"
"}\n"
"\n"
"\n"
"float3 tintSRGBToLinear(float3 c)\n"
"{\n"
"    float3 lo = c / 12.92f;\n"
"    float3 hi = pow(abs((c + 0.055f) / 1.055f), 2.4f);        // abs() keeps FXC from warning, c is never negative.\n"
"\n"
"    return lerp(hi, lo, step(c, 0.04045f));\n"
"}\n"
"\n"
"\n"
"float4 evalTintBlock(StructuredBuffer<float4> buf, uint ofs, float2 pos)\n"
"{\n"
"    float4 result = float4(0.0f, 0.0f, 0.0f, 0.0f);\n"
"\n"
"    uint nLayers = uint(buf[ofs].x);\n"
"    uint p = ofs + 1;\n"
"\n"
"    [loop]\n"
"    for (uint l = 0; l < nLayers; l++)\n"
"    {\n"
"        float4 info = buf[p];\n"
"        float4 geo = buf[p + 1];\n"
"        float srgb = buf[p + 2].x;\n"
"\n"
"        uint nStops = uint(info.z);\n"
"        uint posOfs = p + 3;\n"
"        uint colOfs = posOfs + ((nStops + 3) >> 2);\n"
"\n"
"        [branch]\n"
"        if (nStops > 0)\n"
"        {\n"
"            // Position along the gradient, with spread applied.\n"
"\n"
"            float t;\n"
"\n"
"            if (info.x < 0.5f)\n"
"                t = geo.x * pos.x + geo.y * pos.y + geo.z;\n"
"            else\n"
"                t = length((pos - geo.xy) * geo.zw);\n"
"\n"
"            t = clamp(t, -1e7f, 1e7f);\n"
"\n"
"            uint spread = uint(info.y);\n"
"\n"
"            if (spread == 0)\n"
"                t = saturate(t);\n"
"            else if (spread == 1)\n"
"                t = t - floor(t);\n"
"            else\n"
"            {\n"
"                float r = t - 2.0f * floor(t * 0.5f);\n"
"                t = r > 1.0f ? 2.0f - r : r;\n"
"            }\n"
"\n"
"            // Last stop at or before t. Stops with equal positions make a hard edge.\n"
"\n"
"            int k = -1;\n"
"\n"
"            [loop]\n"
"            for (uint i = 0; i < nStops; i++)\n"
"            {\n"
"                if (tintStopPos(buf, posOfs, i) <= t)\n"
"                    k = int(i);\n"
"            }\n"
"\n"
"            float4 c;\n"
"\n"
"            if (k < 0)\n"
"                c = buf[colOfs];\n"
"            else if (uint(k) == nStops - 1)\n"
"                c = buf[colOfs + uint(k)];\n"
"            else\n"
"            {\n"
"                uint uk = uint(k);\n"
"                float p0 = tintStopPos(buf, posOfs, uk);\n"
"                float p1 = tintStopPos(buf, posOfs, uk + 1);\n"
"\n"
"                c = lerp(buf[colOfs + uk], buf[colOfs + uk + 1], (t - p0) / (p1 - p0));\n"
"            }\n"
"\n"
"            if (srgb > 0.5f)\n"
"                c.rgb = tintSRGBToLinear(c.rgb);\n"
"\n"
"            result += c * info.w;\n"
"        }\n"
"\n"
"        p = colOfs + nStops;\n"
"    }\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"\n"
"// Color of the device tint at a canvas pixel. White when there is no tint.\n"
"\n"
"float4 tintColor(float2 pixelPos)\n"
"{\n"
"    float4 tint = float4(1.0f, 1.0f, 1.0f, 1.0f);\n"
"\n"
"    [branch]\n"
"    if (tintOfs >= 0)\n"
"        tint = evalTintBlock(colors, uint(tintOfs), pixelPos);\n"
"\n"
"    return tint;\n"
"}\n"
"\n"
"cbuffer CanvasInfo : register(b0)\n"
"{\n"
"    float2 canvasScale;     // Not used here.\n"
"    float2 textureSize;     // Not used here.\n"
"    uint flags;             // Not used here.\n"
"    uint blurOfs;           // Not used here.\n"
"    uint edgemapEdges;      // Edges to walk, one fewer than the segments we render.\n"
"    uint edgemapPitch;      // Edges per column in the edgemap's buffer.\n"
"};\n"
"\n"
"// The tint, tintColor() and the colors buffer come from tint.hlsl, which is put\n"
"// in front of this file.\n"
"\n"
"\n"
"StructuredBuffer<float4> edgemap : register(t3);\n"
"\n"
"\n"
"struct PS_INPUT\n"
"{\n"
"    float4 position : SV_POSITION;\n"
"    float4 color : COLOR;\n"
"    float2 texUV : TEXCOORD0;\n"
"    nointerpolation uint2 segColorsOfs : TEXCOORD1;    // Flat colors and tint table in the edgemap buffer.\n"
"};\n"
"\n"
"\n"
"// A segment is colored either by a flat color or by a tint placed in the\n"
"// edgemap's own rectangle. The edgemap buffer has a table with the offset of\n"
"// each segment's tint block, -1 for a flat colored segment.\n"
"\n"
"float4 segmentColor(uint seg, uint2 segColorsOfs, float2 epos)\n"
"{\n"
"    float4 col;\n"
"\n"
"    int blockOfs = int(edgemap[segColorsOfs.y + seg].x);\n"
"\n"
"    [branch]\n"
"    if (blockOfs < 0)\n"
"        col = edgemap[segColorsOfs.x + seg];\n"
"    else\n"
"        col = evalTintBlock(edgemap, uint(blockOfs), epos);\n"
"\n"
"    return col;\n"
"}\n"
"\n"
"\n"
"float4 main(PS_INPUT input) : SV_TARGET\n"
"{\n"
"    // Walking down a column of the edgemap, one edge at a time. Each edge says\n"
"    // where it begins and how steeply it runs, which is enough to tell how much\n"
"    // of this pixel falls above it. The difference between one edge's coverage\n"
"    // and the next is how much of the pixel belongs to the segment between them.\n"
"\n"
"    uint nEdges = edgemapEdges;\n"
"    uint pitch = edgemapPitch;\n"
"\n"
"    uint column = uint(input.texUV.x) * pitch;\n"
"\n"
"    // Pixel center in edgemap space, which is where segment tints are placed.\n"
"    // V is half a pixel back already, see DX12Backend::_drawEdgemap().\n"
"\n"
"    float2 epos = float2(floor(input.texUV.x) + 0.5f, input.texUV.y + 0.5f);\n"
"\n"
"    float totalAlpha = 0.0f;\n"
"    float3 rgbAcc = float3(0.0f, 0.0f, 0.0f);\n"
"\n"
"    float factor = 1.0f;\n"
"\n"
"    [loop]\n"
"    for (uint i = 0; i < nEdges; i++)\n"
"    {\n"
"        float4 col = segmentColor(i, input.segColorsOfs, epos);\n"
"\n"
"        float4 edge = edgemap[column + i];\n"
"\n"
"        float x = (input.texUV.y - edge.r) * edge.g;\n"
"\n"
"        float adder = edge.g / 2.0f;\n"
"\n"
"        if (x < 0.0f)\n"
"            adder = edge.b;\n"
"        else if (x + edge.g > 1.0f)\n"
"            adder = edge.a;\n"
"\n"
"        float factor2 = clamp(x + adder, 0.0f, 1.0f);\n"
"\n"
"        float useFactor = (factor - factor2) * col.a;\n"
"\n"
"        totalAlpha += useFactor;\n"
"        rgbAcc += col.rgb * useFactor;\n"
"\n"
"        factor = factor2;\n"
"    }\n"
"\n"
"    // Whatever is left below the last edge belongs to the last segment.\n"
"\n"
"    float4 lastCol = segmentColor(nEdges, input.segColorsOfs, epos);\n"
"\n"
"    float lastFactor = factor * lastCol.a;\n"
"\n"
"    totalAlpha += lastFactor;\n"
"    rgbAcc += lastCol.rgb * lastFactor;\n"
"\n"
"    float4 outColor;\n"
"\n"
"    outColor.a = totalAlpha;\n"
"    outColor.rgb = totalAlpha > 0.0f ? rgbAcc / totalAlpha : float3(0.0f, 0.0f, 0.0f);\n"
"\n"
"    return outColor * input.color * tintColor(input.position.xy);\n"
"}\n"
;


}
